# automatically generated by the FlatBuffers compiler, do not modify

static func GetRoot( _bytes : PackedByteArray ) -> RootTable:
	return GetRootTable( _bytes, _bytes.decode_u32(0) )

static func GetSubTable( _bytes : PackedByteArray, _start : int  ) -> SubTable:
	if _bytes.is_empty(): return null
	var new_SubTable = SubTable.new()
	new_SubTable.start = _start
	new_SubTable.bytes = _bytes
	return new_SubTable


class SubTable extends FlatBuffer:
	enum vtable{
		VT_ITEM = 4
	}

	func item_is_present() -> bool:
		return get_field_offset( vtable.VT_ITEM )

	func item() -> int:
		var foffset = get_field_offset( vtable.VT_ITEM )
		if not foffset: return 0
		return bytes.decode_s32( start + foffset )


class SubTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_item( item : int ) -> void:
		fbb_.add_element_int_default( SubTable.vtable.VT_ITEM, item, 0 )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateSubTable( _fbb : FlatBufferBuilder,
		item : int ) -> int :
	var builder = SubTableBuilder.new( _fbb );
	builder.add_item( item );
	return builder.finish();

static func GetRootTable( _bytes : PackedByteArray, _start : int = 0 ) -> RootTable:
	if _bytes.is_empty(): return null
	var new_RootTable = RootTable.new()
	new_RootTable.start = _start
	new_RootTable.bytes = _bytes
	return new_RootTable


class RootTable extends FlatBuffer:
	enum vtable{
		VT_SUBTABLE = 4,
		VT_TABLE_ARRAY = 6
	}

	func subtable_is_present() -> bool:
		return get_field_offset( vtable.VT_SUBTABLE )

	func subtable() -> SubTable:
		var field_start = get_field_start( vtable.VT_SUBTABLE )
		if not field_start: return null
		return parent.GetSubTable( bytes, field_start )

	func table_array_is_present() -> bool:
		return get_field_offset( vtable.VT_TABLE_ARRAY )

	func table_array_size() -> int:
		var array_start = get_field_start( vtable.VT_TABLE_ARRAY )
		if not array_start: return 0
		return bytes.decode_u32( array_start )

	func table_array() -> Array:
		var array_start = get_field_start( vtable.VT_TABLE_ARRAY )
		if not array_start: return []
		var array_size = bytes.decode_u32( array_start )
		array_start += 4
		var array : Array; array.resize( array_size )
		for i in array_size:
			var pos = array_start + i * 4
			array[i] = parent.GetSubTable( bytes, pos + bytes.decode_u32( pos ) )
		return array


class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_subtable( subtable_offset : int ) -> void:
		fbb_.add_offset( RootTable.vtable.VT_SUBTABLE, subtable_offset )

	func add_table_array( table_array_offset : int ) -> void:
		fbb_.add_offset( RootTable.vtable.VT_TABLE_ARRAY, table_array_offset )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateRootTable( _fbb : FlatBufferBuilder,
		subtable : int,
		table_array : int ) -> int :
	var builder = RootTableBuilder.new( _fbb );
	builder.add_table_array( table_array );
	builder.add_subtable( subtable );
	return builder.finish();

