# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

static func get_root( _bytes : PackedByteArray ) -> RootTable:
	return get_RootTable( _bytes, _bytes.decode_u32(0) )

class SubTable extends FlatBuffer:
	enum vtable{
		VT_ITEM = 4
	}

	func _init( bytes_ : PackedByteArray = [], start_ : int = 0) -> void:
		bytes = bytes_; start = start_

	# Presence Functions
	func item_is_present() -> bool:
		return get_field_offset( vtable.VT_ITEM )

	# [================[ item ]================]
	func item() -> int:
		var foffset : int = get_field_offset( vtable.VT_ITEM )
		if not foffset: return 0
		return bytes.decode_s32( start + foffset )


class SubTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_item( item : int ) -> void:
		fbb_.add_element_int_default( SubTable.vtable.VT_ITEM, item, 0 )

	func finish() -> int:
		var end : int = fbb_.end_table( start_ )
		var o : int = end
		return o;


class RootTable extends FlatBuffer:
	const _FBTestTableArray_schema = preload( 'FBTestTableArray_generated.gd' )

	enum vtable{
		VT_SUBTABLE = 4,
		VT_TABLE_ARRAY = 6
	}

	func _init( bytes_ : PackedByteArray = [], start_ : int = 0) -> void:
		bytes = bytes_; start = start_

	# Presence Functions
	func subtable_is_present() -> bool:
		return get_field_offset( vtable.VT_SUBTABLE )

	func table_array_is_present() -> bool:
		return get_field_offset( vtable.VT_TABLE_ARRAY )

	# [================[ subtable ]================]
	func subtable() -> _FBTestTableArray_schema.SubTable:
		var field_start : int = get_field_start( vtable.VT_SUBTABLE )
		if not field_start: return null
		return _FBTestTableArray_schema.get_SubTable( bytes, field_start )

	# [================[ table_array ]================]
	func table_array_size() -> int:
		var array_start : int = get_field_start( vtable.VT_TABLE_ARRAY )
		if not array_start: return 0
		return bytes.decode_u32( array_start )

	func table_array() -> Array:
		var array_start : int = get_field_start( vtable.VT_TABLE_ARRAY )
		if not array_start: return []
		var array_size : int = bytes.decode_u32( array_start )
		array_start += 4
		var array : Array
		if array.resize( array_size ) != OK: return []
		for i : int in array_size:
			var p : int = array_start + i * 4
			array[i] = _FBTestTableArray_schema.get_SubTable( bytes, p + bytes.decode_u32( p ) )
		return array

	func table_array_at( idx : int, into : SubTable = null ) -> SubTable:
		var field_start : int = get_field_start( vtable.VT_TABLE_ARRAY )
		var array_size : int = bytes.decode_u32( field_start )
		var array_start : int = field_start + 4
		assert(field_start, 'Field is not present in buffer' )
		assert( idx < array_size, 'index is out of bounds')
		var relative_offset : int = array_start + idx * 4
		var offset : int = relative_offset + bytes.decode_u32( relative_offset )
		if into:
			into.bytes = bytes
			into.start = relative_offset
			return into
		return _FBTestTableArray_schema.get_SubTable( bytes, offset )


class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_subtable( subtable_offset : int ) -> void:
		fbb_.add_offset( RootTable.vtable.VT_SUBTABLE, subtable_offset )

	func add_table_array( table_array_offset : int ) -> void:
		fbb_.add_offset( RootTable.vtable.VT_TABLE_ARRAY, table_array_offset )

	func finish() -> int:
		var end : int = fbb_.end_table( start_ )
		var o : int = end
		return o;


static func get_SubTable( _bytes : PackedByteArray, _start : int = 0 ) -> SubTable:
	assert(not _bytes.is_empty())
	return SubTable.new(_bytes, _start)

static func create_SubTable( _fbb : FlatBufferBuilder,
		item : int ) -> int :
	var builder : SubTableBuilder = SubTableBuilder.new( _fbb );
	builder.add_item( item );
	return builder.finish();

static func get_RootTable( _bytes : PackedByteArray, _start : int = 0 ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _start)

static func create_RootTable( _fbb : FlatBufferBuilder,
		subtable : int,
		table_array : int ) -> int :
	var builder : RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_table_array( table_array );
	builder.add_subtable( subtable );
	return builder.finish();

