# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class TestTable extends FlatBuffer:
	enum vtable{
		VT_FBOOL = 4,
		VT_FINT8 = 6,
		VT_FINT16 = 8,
		VT_FUINT16 = 10,
		VT_FUINT32 = 12,
		VT_FINT64 = 14,
		VT_FUINT8 = 16,
		VT_FINT32 = 18,
		VT_FUINT64 = 20,
		VT_FFLOAT32 = 22,
		VT_FFLOAT64 = 24,
		VT_FSTRING = 26,
		VT_FCOLOR = 28,
		VT_FVECTOR2 = 30,
		VT_FVECTOR3 = 32,
		VT_FVECTOR4 = 34,
		VT_FAABB = 36,
		VT_FBASIS = 38,
		VT_FPLANE = 40,
		VT_FPROJECTION = 42,
		VT_FQUATERNION = 44,
		VT_FRECT2 = 46,
		VT_FRECT2I = 48,
		VT_FTRANSFORM2D = 50,
		VT_FTRANSFORM3D = 52,
		VT_FVECTOR2I = 54,
		VT_FVECTOR3I = 56,
		VT_FVECTOR4I = 58
	}

	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	# Presence Functions
	func fbool_is_present() -> bool:
		return get_field_offset( vtable.VT_FBOOL )

	func fint8_is_present() -> bool:
		return get_field_offset( vtable.VT_FINT8 )

	func fint16_is_present() -> bool:
		return get_field_offset( vtable.VT_FINT16 )

	func fuint16_is_present() -> bool:
		return get_field_offset( vtable.VT_FUINT16 )

	func fuint32_is_present() -> bool:
		return get_field_offset( vtable.VT_FUINT32 )

	func fint64_is_present() -> bool:
		return get_field_offset( vtable.VT_FINT64 )

	func fuint8_is_present() -> bool:
		return get_field_offset( vtable.VT_FUINT8 )

	func fint32_is_present() -> bool:
		return get_field_offset( vtable.VT_FINT32 )

	func fuint64_is_present() -> bool:
		return get_field_offset( vtable.VT_FUINT64 )

	func ffloat32_is_present() -> bool:
		return get_field_offset( vtable.VT_FFLOAT32 )

	func ffloat64_is_present() -> bool:
		return get_field_offset( vtable.VT_FFLOAT64 )

	func fstring_is_present() -> bool:
		return get_field_offset( vtable.VT_FSTRING )

	func fcolor_is_present() -> bool:
		return get_field_offset( vtable.VT_FCOLOR )

	func fvector2_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR2 )

	func fvector3_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR3 )

	func fvector4_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR4 )

	func faabb_is_present() -> bool:
		return get_field_offset( vtable.VT_FAABB )

	func fbasis_is_present() -> bool:
		return get_field_offset( vtable.VT_FBASIS )

	func fplane_is_present() -> bool:
		return get_field_offset( vtable.VT_FPLANE )

	func fprojection_is_present() -> bool:
		return get_field_offset( vtable.VT_FPROJECTION )

	func fquaternion_is_present() -> bool:
		return get_field_offset( vtable.VT_FQUATERNION )

	func frect2_is_present() -> bool:
		return get_field_offset( vtable.VT_FRECT2 )

	func frect2i_is_present() -> bool:
		return get_field_offset( vtable.VT_FRECT2I )

	func ftransform2d_is_present() -> bool:
		return get_field_offset( vtable.VT_FTRANSFORM2D )

	func ftransform3d_is_present() -> bool:
		return get_field_offset( vtable.VT_FTRANSFORM3D )

	func fvector2i_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR2I )

	func fvector3i_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR3I )

	func fvector4i_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR4I )

	# [================[ fbool ]================]
	func fbool_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FBOOL )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fbool() -> Array:
		var array_start: int = get_field_start( vtable.VT_FBOOL )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	func fbool_at( index: int ) -> bool:
		var array_start: int = get_field_start( vtable.VT_FBOOL )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes[array_start + index]

	# [================[ fint8 ]================]
	func fint8_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FINT8 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fint8() -> Array:
		var array_start: int = get_field_start( vtable.VT_FINT8 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_s8( array_start + i * 1)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array

	func fint8_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FINT8 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_s8( array_start + index * 1)

	# [================[ fint16 ]================]
	func fint16_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FINT16 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fint16() -> Array:
		var array_start: int = get_field_start( vtable.VT_FINT16 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_s16( array_start + i * 2)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array

	func fint16_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FINT16 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_s16( array_start + index * 2)

	# [================[ fuint16 ]================]
	func fuint16_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT16 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fuint16() -> Array:
		var array_start: int = get_field_start( vtable.VT_FUINT16 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_u16( array_start + i * 2)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array

	func fuint16_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT16 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_u16( array_start + index * 2)

	# [================[ fuint32 ]================]
	func fuint32_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT32 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fuint32() -> Array:
		var array_start: int = get_field_start( vtable.VT_FUINT32 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_u32( array_start + i * 4)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array

	func fuint32_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT32 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_u32( array_start + index * 4)

	# [================[ fint64 ]================]
	func fint64_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FINT64 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fint64() -> PackedInt64Array:
		var array_start: int = get_field_start( vtable.VT_FINT64 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 8
		return _fb_bytes.slice( array_start, array_end ).to_int64_array()

	func fint64_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FINT64 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_s64( array_start + index * 8)

	# [================[ fuint8 ]================]
	func fuint8_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT8 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fuint8() -> PackedByteArray:
		var array_start: int = get_field_start( vtable.VT_FUINT8 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	func fuint8_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT8 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes[array_start + index]

	# [================[ fint32 ]================]
	func fint32_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FINT32 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fint32() -> PackedInt32Array:
		var array_start: int = get_field_start( vtable.VT_FINT32 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 4
		return _fb_bytes.slice( array_start, array_end ).to_int32_array()

	func fint32_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FINT32 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_s32( array_start + index * 4)

	# [================[ fuint64 ]================]
	func fuint64_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT64 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fuint64() -> Array:
		var array_start: int = get_field_start( vtable.VT_FUINT64 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_u64( array_start + i * 8)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array

	func fuint64_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_FUINT64 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_u64( array_start + index * 8)

	# [================[ ffloat32 ]================]
	func ffloat32_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FFLOAT32 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func ffloat32() -> PackedFloat32Array:
		var array_start: int = get_field_start( vtable.VT_FFLOAT32 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 4
		return _fb_bytes.slice( array_start, array_end ).to_float32_array()

	func ffloat32_at( index: int ) -> float:
		var array_start: int = get_field_start( vtable.VT_FFLOAT32 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_float( array_start + index * 4)

	# [================[ ffloat64 ]================]
	func ffloat64_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FFLOAT64 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func ffloat64() -> PackedFloat64Array:
		var array_start: int = get_field_start( vtable.VT_FFLOAT64 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 8
		return _fb_bytes.slice( array_start, array_end ).to_float64_array()

	func ffloat64_at( index: int ) -> float:
		var array_start: int = get_field_start( vtable.VT_FFLOAT64 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_double( array_start + index * 8)

	# [================[ fstring ]================]
	func fstring_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FSTRING )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fstring() -> PackedStringArray:
		var array_start: int = get_field_start( vtable.VT_FSTRING )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: PackedStringArray
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var idx: int = array_start + i * 4
			var element_start: int = idx + _fb_bytes.decode_u32( idx )
			array[i] = decode_String( element_start )
		return array

	func fstring_at( index: int ) -> String:
		var array_start: int = get_field_start( vtable.VT_FSTRING )
		if not array_start: return ''
		array_start += 4
		var string_start: int = array_start + index * 4
		string_start += _fb_bytes.decode_u32( string_start )
		return decode_String( string_start )

	# [================[ fcolor ]================]
	func fcolor_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FCOLOR )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fcolor() -> PackedColorArray:
		var field_start: int = get_field_start( vtable.VT_FCOLOR )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 16 ) \
				.to_color_array()

	func fcolor_at( idx: int ) -> Color:
		var field_start: int = get_field_start( vtable.VT_FCOLOR )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Color( array_start + idx * 16 )

	# [================[ fvector2 ]================]
	func fvector2_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FVECTOR2 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fvector2() -> PackedVector2Array:
		var field_start: int = get_field_start( vtable.VT_FVECTOR2 )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 8 ) \
				.to_vector2_array()

	func fvector2_at( idx: int ) -> Vector2:
		var field_start: int = get_field_start( vtable.VT_FVECTOR2 )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector2( array_start + idx * 8 )

	# [================[ fvector3 ]================]
	func fvector3_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FVECTOR3 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fvector3() -> PackedVector3Array:
		var field_start: int = get_field_start( vtable.VT_FVECTOR3 )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 12 ) \
				.to_vector3_array()

	func fvector3_at( idx: int ) -> Vector3:
		var field_start: int = get_field_start( vtable.VT_FVECTOR3 )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector3( array_start + idx * 12 )

	# [================[ fvector4 ]================]
	func fvector4_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FVECTOR4 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fvector4() -> PackedVector4Array:
		var field_start: int = get_field_start( vtable.VT_FVECTOR4 )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 16 ) \
				.to_vector4_array()

	func fvector4_at( idx: int ) -> Vector4:
		var field_start: int = get_field_start( vtable.VT_FVECTOR4 )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector4( array_start + idx * 16 )

	# [================[ faabb ]================]
	func faabb_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FAABB )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func faabb() -> Array[AABB]:
		var field_start: int = get_field_start( vtable.VT_FAABB )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[AABB]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_AABB( array_start + i * 24)
		return array

	func faabb_at( idx: int ) -> AABB:
		var field_start: int = get_field_start( vtable.VT_FAABB )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_AABB( array_start + idx * 24 )

	# [================[ fbasis ]================]
	func fbasis_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FBASIS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fbasis() -> Array[Basis]:
		var field_start: int = get_field_start( vtable.VT_FBASIS )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Basis]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Basis( array_start + i * 36)
		return array

	func fbasis_at( idx: int ) -> Basis:
		var field_start: int = get_field_start( vtable.VT_FBASIS )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Basis( array_start + idx * 36 )

	# [================[ fplane ]================]
	func fplane_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FPLANE )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fplane() -> Array[Plane]:
		var field_start: int = get_field_start( vtable.VT_FPLANE )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Plane]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Plane( array_start + i * 16)
		return array

	func fplane_at( idx: int ) -> Plane:
		var field_start: int = get_field_start( vtable.VT_FPLANE )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Plane( array_start + idx * 16 )

	# [================[ fprojection ]================]
	func fprojection_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FPROJECTION )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fprojection() -> Array[Projection]:
		var field_start: int = get_field_start( vtable.VT_FPROJECTION )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Projection]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Projection( array_start + i * 64)
		return array

	func fprojection_at( idx: int ) -> Projection:
		var field_start: int = get_field_start( vtable.VT_FPROJECTION )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Projection( array_start + idx * 64 )

	# [================[ fquaternion ]================]
	func fquaternion_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FQUATERNION )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fquaternion() -> Array[Quaternion]:
		var field_start: int = get_field_start( vtable.VT_FQUATERNION )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Quaternion]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Quaternion( array_start + i * 16)
		return array

	func fquaternion_at( idx: int ) -> Quaternion:
		var field_start: int = get_field_start( vtable.VT_FQUATERNION )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Quaternion( array_start + idx * 16 )

	# [================[ frect2 ]================]
	func frect2_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FRECT2 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func frect2() -> Array[Rect2]:
		var field_start: int = get_field_start( vtable.VT_FRECT2 )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Rect2]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Rect2( array_start + i * 16)
		return array

	func frect2_at( idx: int ) -> Rect2:
		var field_start: int = get_field_start( vtable.VT_FRECT2 )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Rect2( array_start + idx * 16 )

	# [================[ frect2i ]================]
	func frect2i_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FRECT2I )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func frect2i() -> Array[Rect2i]:
		var field_start: int = get_field_start( vtable.VT_FRECT2I )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Rect2i]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Rect2i( array_start + i * 16)
		return array

	func frect2i_at( idx: int ) -> Rect2i:
		var field_start: int = get_field_start( vtable.VT_FRECT2I )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Rect2i( array_start + idx * 16 )

	# [================[ ftransform2d ]================]
	func ftransform2d_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FTRANSFORM2D )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func ftransform2d() -> Array[Transform2D]:
		var field_start: int = get_field_start( vtable.VT_FTRANSFORM2D )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Transform2D]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Transform2D( array_start + i * 24)
		return array

	func ftransform2d_at( idx: int ) -> Transform2D:
		var field_start: int = get_field_start( vtable.VT_FTRANSFORM2D )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Transform2D( array_start + idx * 24 )

	# [================[ ftransform3d ]================]
	func ftransform3d_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FTRANSFORM3D )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func ftransform3d() -> Array[Transform3D]:
		var field_start: int = get_field_start( vtable.VT_FTRANSFORM3D )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Transform3D]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Transform3D( array_start + i * 48)
		return array

	func ftransform3d_at( idx: int ) -> Transform3D:
		var field_start: int = get_field_start( vtable.VT_FTRANSFORM3D )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Transform3D( array_start + idx * 48 )

	# [================[ fvector2i ]================]
	func fvector2i_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FVECTOR2I )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fvector2i() -> Array[Vector2i]:
		var field_start: int = get_field_start( vtable.VT_FVECTOR2I )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Vector2i]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Vector2i( array_start + i * 8)
		return array

	func fvector2i_at( idx: int ) -> Vector2i:
		var field_start: int = get_field_start( vtable.VT_FVECTOR2I )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector2i( array_start + idx * 8 )

	# [================[ fvector3i ]================]
	func fvector3i_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FVECTOR3I )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fvector3i() -> Array[Vector3i]:
		var field_start: int = get_field_start( vtable.VT_FVECTOR3I )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Vector3i]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Vector3i( array_start + i * 12)
		return array

	func fvector3i_at( idx: int ) -> Vector3i:
		var field_start: int = get_field_start( vtable.VT_FVECTOR3I )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector3i( array_start + idx * 12 )

	# [================[ fvector4i ]================]
	func fvector4i_size() -> int:
		var array_start: int = get_field_start( vtable.VT_FVECTOR4I )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func fvector4i() -> Array[Vector4i]:
		var field_start: int = get_field_start( vtable.VT_FVECTOR4I )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[Vector4i]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = decode_Vector4i( array_start + i * 16)
		return array

	func fvector4i_at( idx: int ) -> Vector4i:
		var field_start: int = get_field_start( vtable.VT_FVECTOR4I )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector4i( array_start + idx * 16 )


class TestTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_fbool( fbool_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FBOOL, fbool_offset )

	func add_fint8( fint8_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FINT8, fint8_offset )

	func add_fint16( fint16_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FINT16, fint16_offset )

	func add_fuint16( fuint16_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FUINT16, fuint16_offset )

	func add_fuint32( fuint32_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FUINT32, fuint32_offset )

	func add_fint64( fint64_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FINT64, fint64_offset )

	func add_fuint8( fuint8_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FUINT8, fuint8_offset )

	func add_fint32( fint32_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FINT32, fint32_offset )

	func add_fuint64( fuint64_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FUINT64, fuint64_offset )

	func add_ffloat32( ffloat32_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FFLOAT32, ffloat32_offset )

	func add_ffloat64( ffloat64_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FFLOAT64, ffloat64_offset )

	func add_fstring( fstring_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FSTRING, fstring_offset )

	func add_fcolor( fcolor_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FCOLOR, fcolor_offset )

	func add_fvector2( fvector2_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FVECTOR2, fvector2_offset )

	func add_fvector3( fvector3_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FVECTOR3, fvector3_offset )

	func add_fvector4( fvector4_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FVECTOR4, fvector4_offset )

	func add_faabb( faabb_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FAABB, faabb_offset )

	func add_fbasis( fbasis_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FBASIS, fbasis_offset )

	func add_fplane( fplane_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FPLANE, fplane_offset )

	func add_fprojection( fprojection_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FPROJECTION, fprojection_offset )

	func add_fquaternion( fquaternion_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FQUATERNION, fquaternion_offset )

	func add_frect2( frect2_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FRECT2, frect2_offset )

	func add_frect2i( frect2i_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FRECT2I, frect2i_offset )

	func add_ftransform2d( ftransform2d_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FTRANSFORM2D, ftransform2d_offset )

	func add_ftransform3d( ftransform3d_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FTRANSFORM3D, ftransform3d_offset )

	func add_fvector2i( fvector2i_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FVECTOR2I, fvector2i_offset )

	func add_fvector3i( fvector3i_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FVECTOR3I, fvector3i_offset )

	func add_fvector4i( fvector4i_offset: int ) -> void:
		fbb_.add_offset( TestTable.vtable.VT_FVECTOR4I, fvector4i_offset )

	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;


static func create_TestTable( _fbb: FlatBufferBuilder,
		fbool: int,
		fint8: int,
		fint16: int,
		fuint16: int,
		fuint32: int,
		fint64: int,
		fuint8: int,
		fint32: int,
		fuint64: int,
		ffloat32: int,
		ffloat64: int,
		fstring: int,
		fcolor: int,
		fvector2: int,
		fvector3: int,
		fvector4: int,
		faabb: int,
		fbasis: int,
		fplane: int,
		fprojection: int,
		fquaternion: int,
		frect2: int,
		frect2i: int,
		ftransform2d: int,
		ftransform3d: int,
		fvector2i: int,
		fvector3i: int,
		fvector4i: int ) -> int :
	var builder: TestTableBuilder = TestTableBuilder.new( _fbb );
	builder.add_fvector4i( fvector4i );
	builder.add_fvector3i( fvector3i );
	builder.add_fvector2i( fvector2i );
	builder.add_ftransform3d( ftransform3d );
	builder.add_ftransform2d( ftransform2d );
	builder.add_frect2i( frect2i );
	builder.add_frect2( frect2 );
	builder.add_fquaternion( fquaternion );
	builder.add_fprojection( fprojection );
	builder.add_fplane( fplane );
	builder.add_fbasis( fbasis );
	builder.add_faabb( faabb );
	builder.add_fvector4( fvector4 );
	builder.add_fvector3( fvector3 );
	builder.add_fvector2( fvector2 );
	builder.add_fcolor( fcolor );
	builder.add_fstring( fstring );
	builder.add_ffloat64( ffloat64 );
	builder.add_ffloat32( ffloat32 );
	builder.add_fuint64( fuint64 );
	builder.add_fint32( fint32 );
	builder.add_fuint8( fuint8 );
	builder.add_fint64( fint64 );
	builder.add_fuint32( fuint32 );
	builder.add_fuint16( fuint16 );
	builder.add_fint16( fint16 );
	builder.add_fint8( fint8 );
	builder.add_fbool( fbool );
	return builder.finish();

static func get_TestTable( _bytes: PackedByteArray ) -> TestTable:
	assert(not _bytes.is_empty())
	return TestTable.new(_bytes, _bytes.decode_u32(0))
