# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

static func get_root( _bytes : PackedByteArray ) -> RootTable:
	return get_RootTable( _bytes, _bytes.decode_u32(0) )

static func create_CustomStruct(
		_x : int,
		_y : float ) -> CustomStruct :
	var val : CustomStruct = CustomStruct.new()
	val.y = _y;
	val.x = _x;
	return val

class CustomStruct extends FlatBuffer:
	const size : int = 8

	func _init( bytes_ : PackedByteArray = [], start_ : int = 0) -> void:
		if bytes_.is_empty(): 
			bytes = PackedByteArray()
			bytes.resize( size )
		else:
			assert(start_ + size <= bytes_.size())
			bytes = bytes_; start = start_

	# [================[ x ]================]
	var x : int :
		get(): return bytes.decode_s32(start + 0)
		set(v): bytes.encode_s32(start + 0, v)

	# [================[ y ]================]
	var y : float :
		get(): return bytes.decode_float(start + 4)
		set(v): bytes.encode_float(start + 4, v)


class RootTable extends FlatBuffer:
	enum vtable{
		VT_FAABB = 4,
		VT_FBASIS = 6,
		VT_FCOLOR = 8,
		VT_FPLANE = 10,
		VT_FPROJECTION = 12,
		VT_FQUATERNION = 14,
		VT_FRECT2 = 16,
		VT_FRECT2I = 18,
		VT_FTRANSFORM2D = 20,
		VT_FTRANSFORM3D = 22,
		VT_FVECTOR2 = 24,
		VT_FVECTOR2I = 26,
		VT_FVECTOR3 = 28,
		VT_FVECTOR3I = 30,
		VT_FVECTOR4 = 32,
		VT_VECTOR4I = 34
	}

	func _init( bytes_ : PackedByteArray = [], start_ : int = 0) -> void:
		bytes = bytes_; start = start_

	# Presence Functions
	func faabb_is_present() -> bool:
		return get_field_offset( vtable.VT_FAABB )

	func fbasis_is_present() -> bool:
		return get_field_offset( vtable.VT_FBASIS )

	func fcolor_is_present() -> bool:
		return get_field_offset( vtable.VT_FCOLOR )

	func fplane_is_present() -> bool:
		return get_field_offset( vtable.VT_FPLANE )

	func fprojection_is_present() -> bool:
		return get_field_offset( vtable.VT_FPROJECTION )

	func fquaternion_is_present() -> bool:
		return get_field_offset( vtable.VT_FQUATERNION )

	func frect2_is_present() -> bool:
		return get_field_offset( vtable.VT_FRECT2 )

	func frect2i_is_present() -> bool:
		return get_field_offset( vtable.VT_FRECT2I )

	func ftransform2d_is_present() -> bool:
		return get_field_offset( vtable.VT_FTRANSFORM2D )

	func ftransform3d_is_present() -> bool:
		return get_field_offset( vtable.VT_FTRANSFORM3D )

	func fvector2_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR2 )

	func fvector2i_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR2I )

	func fvector3_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR3 )

	func fvector3i_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR3I )

	func fvector4_is_present() -> bool:
		return get_field_offset( vtable.VT_FVECTOR4 )

	func vector4i_is_present() -> bool:
		return get_field_offset( vtable.VT_VECTOR4I )

	# [================[ faabb ]================]
	func faabb() -> AABB:
		return get_AABB( vtable.VT_FAABB )

	# [================[ fbasis ]================]
	func fbasis() -> Basis:
		return get_Basis( vtable.VT_FBASIS )

	# [================[ fcolor ]================]
	func fcolor() -> Color:
		return get_Color( vtable.VT_FCOLOR )

	# [================[ fplane ]================]
	func fplane() -> Plane:
		return get_Plane( vtable.VT_FPLANE )

	# [================[ fprojection ]================]
	func fprojection() -> Projection:
		return get_Projection( vtable.VT_FPROJECTION )

	# [================[ fquaternion ]================]
	func fquaternion() -> Quaternion:
		return get_Quaternion( vtable.VT_FQUATERNION )

	# [================[ frect2 ]================]
	func frect2() -> Rect2:
		return get_Rect2( vtable.VT_FRECT2 )

	# [================[ frect2i ]================]
	func frect2i() -> Rect2i:
		return get_Rect2i( vtable.VT_FRECT2I )

	# [================[ ftransform2d ]================]
	func ftransform2d() -> Transform2D:
		return get_Transform2D( vtable.VT_FTRANSFORM2D )

	# [================[ ftransform3d ]================]
	func ftransform3d() -> Transform3D:
		return get_Transform3D( vtable.VT_FTRANSFORM3D )

	# [================[ fvector2 ]================]
	func fvector2() -> Vector2:
		return get_Vector2( vtable.VT_FVECTOR2 )

	# [================[ fvector2i ]================]
	func fvector2i() -> Vector2i:
		return get_Vector2i( vtable.VT_FVECTOR2I )

	# [================[ fvector3 ]================]
	func fvector3() -> Vector3:
		return get_Vector3( vtable.VT_FVECTOR3 )

	# [================[ fvector3i ]================]
	func fvector3i() -> Vector3i:
		return get_Vector3i( vtable.VT_FVECTOR3I )

	# [================[ fvector4 ]================]
	func fvector4() -> Vector4:
		return get_Vector4( vtable.VT_FVECTOR4 )

	# [================[ vector4i ]================]
	func vector4i() -> Vector4i:
		return get_Vector4i( vtable.VT_VECTOR4I )


class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_faabb( faabb : AABB ) -> void:
		fbb_.add_AABB( RootTable.vtable.VT_FAABB, faabb )

	func add_fbasis( fbasis : Basis ) -> void:
		fbb_.add_Basis( RootTable.vtable.VT_FBASIS, fbasis )

	func add_fcolor( fcolor : Color ) -> void:
		fbb_.add_Color( RootTable.vtable.VT_FCOLOR, fcolor )

	func add_fplane( fplane : Plane ) -> void:
		fbb_.add_Plane( RootTable.vtable.VT_FPLANE, fplane )

	func add_fprojection( fprojection : Projection ) -> void:
		fbb_.add_Projection( RootTable.vtable.VT_FPROJECTION, fprojection )

	func add_fquaternion( fquaternion : Quaternion ) -> void:
		fbb_.add_Quaternion( RootTable.vtable.VT_FQUATERNION, fquaternion )

	func add_frect2( frect2 : Rect2 ) -> void:
		fbb_.add_Rect2( RootTable.vtable.VT_FRECT2, frect2 )

	func add_frect2i( frect2i : Rect2i ) -> void:
		fbb_.add_Rect2i( RootTable.vtable.VT_FRECT2I, frect2i )

	func add_ftransform2d( ftransform2d : Transform2D ) -> void:
		fbb_.add_Transform2D( RootTable.vtable.VT_FTRANSFORM2D, ftransform2d )

	func add_ftransform3d( ftransform3d : Transform3D ) -> void:
		fbb_.add_Transform3D( RootTable.vtable.VT_FTRANSFORM3D, ftransform3d )

	func add_fvector2( fvector2 : Vector2 ) -> void:
		fbb_.add_Vector2( RootTable.vtable.VT_FVECTOR2, fvector2 )

	func add_fvector2i( fvector2i : Vector2i ) -> void:
		fbb_.add_Vector2i( RootTable.vtable.VT_FVECTOR2I, fvector2i )

	func add_fvector3( fvector3 : Vector3 ) -> void:
		fbb_.add_Vector3( RootTable.vtable.VT_FVECTOR3, fvector3 )

	func add_fvector3i( fvector3i : Vector3i ) -> void:
		fbb_.add_Vector3i( RootTable.vtable.VT_FVECTOR3I, fvector3i )

	func add_fvector4( fvector4 : Vector4 ) -> void:
		fbb_.add_Vector4( RootTable.vtable.VT_FVECTOR4, fvector4 )

	func add_vector4i( vector4i : Vector4i ) -> void:
		fbb_.add_Vector4i( RootTable.vtable.VT_VECTOR4I, vector4i )

	func finish() -> int:
		var end : int = fbb_.end_table( start_ )
		var o : int = end
		return o;


static func get_CustomStruct( _bytes : PackedByteArray, _start : int = 0 ) -> CustomStruct:
	assert(not _bytes.is_empty())
	return CustomStruct.new(_bytes, _start)

static func get_RootTable( _bytes : PackedByteArray, _start : int = 0 ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _start)

static func create_RootTable( _fbb : FlatBufferBuilder,
		faabb : AABB,
		fbasis : Basis,
		fcolor : Color,
		fplane : Plane,
		fprojection : Projection,
		fquaternion : Quaternion,
		frect2 : Rect2,
		frect2i : Rect2i,
		ftransform2d : Transform2D,
		ftransform3d : Transform3D,
		fvector2 : Vector2,
		fvector2i : Vector2i,
		fvector3 : Vector3,
		fvector3i : Vector3i,
		fvector4 : Vector4,
		vector4i : Vector4i ) -> int :
	var builder : RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_vector4i( vector4i );
	builder.add_fvector4( fvector4 );
	builder.add_fvector3i( fvector3i );
	builder.add_fvector3( fvector3 );
	builder.add_fvector2i( fvector2i );
	builder.add_fvector2( fvector2 );
	builder.add_ftransform3d( ftransform3d );
	builder.add_ftransform2d( ftransform2d );
	builder.add_frect2i( frect2i );
	builder.add_frect2( frect2 );
	builder.add_fquaternion( fquaternion );
	builder.add_fprojection( fprojection );
	builder.add_fplane( fplane );
	builder.add_fcolor( fcolor );
	builder.add_fbasis( fbasis );
	builder.add_faabb( faabb );
	return builder.finish();
