# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class RootTable extends FlatBuffer:
	enum {
		VT_BOOLEAN = 4,
		VT_INTEGER = 6,
		VT_FLOATING_POINT = 8,
		VT_STRING = 10,
		VT_VECTOR2 = 12,
		VT_VECTOR2I = 14,
		VT_RECT2 = 16,
		VT_RECT2I = 18,
		VT_VECTOR3 = 20,
		VT_VECTOR3I = 22,
		VT_TRANSFORM2D = 24,
		VT_VECTOR4 = 26,
		VT_VECTOR4I = 28,
		VT_PLANE = 30,
		VT_QUATERNION = 32,
		VT_AABB = 34,
		VT_BASIS = 36,
		VT_TRANSFORM3D = 38,
		VT_PROJECTION = 40,
		VT_COLOR = 42,
		VT_PACKED_BYTE_ARRAY_ = 44,
		VT_PACKED_INT32_ARRAY_ = 46,
		VT_PACKED_INT64_ARRAY_ = 48,
		VT_PACKED_FLOAT32_ARRAY_ = 50,
		VT_PACKED_FLOAT64_ARRAY_ = 52,
		VT_PACKED_STRING_ARRAY_ = 54,
		VT_PACKED_VECTOR2_ARRAY_ = 56,
		VT_PACKED_VECTOR3_ARRAY_ = 58,
		VT_PACKED_COLOR_ARRAY_ = 60,
		VT_PACKED_VECTOR4_ARRAY_ = 62
	}

	## TODO: create a useful doc comment for the init function
	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	## Return true if boolean is present in the buffer, else false
	func boolean_is_present() -> bool:
		return get_field_offset( VT_BOOLEAN )

	func boolean() -> bool:
		var field_start: int = get_inline_field_start( VT_BOOLEAN )
		if not field_start: return 0
		return _fb_bytes.decode_u8( field_start )

	## Return true if integer is present in the buffer, else false
	func integer_is_present() -> bool:
		return get_field_offset( VT_INTEGER )

	func integer() -> int:
		var field_start: int = get_inline_field_start( VT_INTEGER )
		if not field_start: return 0
		return _fb_bytes.decode_s64( field_start )

	## Return true if floating_point is present in the buffer, else false
	func floating_point_is_present() -> bool:
		return get_field_offset( VT_FLOATING_POINT )

	func floating_point() -> float:
		var field_start: int = get_inline_field_start( VT_FLOATING_POINT )
		if not field_start: return 0.0
		return _fb_bytes.decode_double( field_start )

	## Return true if string is present in the buffer, else false
	func string_is_present() -> bool:
		return get_field_offset( VT_STRING )

	func string() -> String:
		var field_start: int = get_offset_field_start( VT_STRING )
		if not field_start: return ''
		return decode_variant( field_start, TYPE_STRING )

	## Return true if vector2 is present in the buffer, else false
	func vector2_is_present() -> bool:
		return get_field_offset( VT_VECTOR2 )

	func vector2() -> Vector2:
		var field_start: int = get_inline_field_start( VT_VECTOR2 )
		return decode_variant( field_start, TYPE_VECTOR2 )

	## Return true if vector2i is present in the buffer, else false
	func vector2i_is_present() -> bool:
		return get_field_offset( VT_VECTOR2I )

	func vector2i() -> Vector2i:
		var field_start: int = get_inline_field_start( VT_VECTOR2I )
		return decode_variant( field_start, TYPE_VECTOR2I )

	## Return true if rect2 is present in the buffer, else false
	func rect2_is_present() -> bool:
		return get_field_offset( VT_RECT2 )

	func rect2() -> Rect2:
		var field_start: int = get_inline_field_start( VT_RECT2 )
		return decode_variant( field_start, TYPE_RECT2 )

	## Return true if rect2i is present in the buffer, else false
	func rect2i_is_present() -> bool:
		return get_field_offset( VT_RECT2I )

	func rect2i() -> Rect2i:
		var field_start: int = get_inline_field_start( VT_RECT2I )
		return decode_variant( field_start, TYPE_RECT2I )

	## Return true if vector3 is present in the buffer, else false
	func vector3_is_present() -> bool:
		return get_field_offset( VT_VECTOR3 )

	func vector3() -> Vector3:
		var field_start: int = get_inline_field_start( VT_VECTOR3 )
		return decode_variant( field_start, TYPE_VECTOR3 )

	## Return true if vector3i is present in the buffer, else false
	func vector3i_is_present() -> bool:
		return get_field_offset( VT_VECTOR3I )

	func vector3i() -> Vector3i:
		var field_start: int = get_inline_field_start( VT_VECTOR3I )
		return decode_variant( field_start, TYPE_VECTOR3I )

	## Return true if transform2d is present in the buffer, else false
	func transform2d_is_present() -> bool:
		return get_field_offset( VT_TRANSFORM2D )

	func transform2d() -> Transform2D:
		var field_start: int = get_inline_field_start( VT_TRANSFORM2D )
		return decode_variant( field_start, TYPE_TRANSFORM2D )

	## Return true if vector4 is present in the buffer, else false
	func vector4_is_present() -> bool:
		return get_field_offset( VT_VECTOR4 )

	func vector4() -> Vector4:
		var field_start: int = get_inline_field_start( VT_VECTOR4 )
		return decode_variant( field_start, TYPE_VECTOR4 )

	## Return true if vector4i is present in the buffer, else false
	func vector4i_is_present() -> bool:
		return get_field_offset( VT_VECTOR4I )

	func vector4i() -> Vector4i:
		var field_start: int = get_inline_field_start( VT_VECTOR4I )
		return decode_variant( field_start, TYPE_VECTOR4I )

	## Return true if plane is present in the buffer, else false
	func plane_is_present() -> bool:
		return get_field_offset( VT_PLANE )

	func plane() -> Plane:
		var field_start: int = get_inline_field_start( VT_PLANE )
		return decode_variant( field_start, TYPE_PLANE )

	## Return true if quaternion is present in the buffer, else false
	func quaternion_is_present() -> bool:
		return get_field_offset( VT_QUATERNION )

	func quaternion() -> Quaternion:
		var field_start: int = get_inline_field_start( VT_QUATERNION )
		return decode_variant( field_start, TYPE_QUATERNION )

	## Return true if aabb is present in the buffer, else false
	func aabb_is_present() -> bool:
		return get_field_offset( VT_AABB )

	func aabb() -> AABB:
		var field_start: int = get_inline_field_start( VT_AABB )
		return decode_variant( field_start, TYPE_AABB )

	## Return true if basis is present in the buffer, else false
	func basis_is_present() -> bool:
		return get_field_offset( VT_BASIS )

	func basis() -> Basis:
		var field_start: int = get_inline_field_start( VT_BASIS )
		return decode_variant( field_start, TYPE_BASIS )

	## Return true if transform3d is present in the buffer, else false
	func transform3d_is_present() -> bool:
		return get_field_offset( VT_TRANSFORM3D )

	func transform3d() -> Transform3D:
		var field_start: int = get_inline_field_start( VT_TRANSFORM3D )
		return decode_variant( field_start, TYPE_TRANSFORM3D )

	## Return true if projection is present in the buffer, else false
	func projection_is_present() -> bool:
		return get_field_offset( VT_PROJECTION )

	func projection() -> Projection:
		var field_start: int = get_inline_field_start( VT_PROJECTION )
		return decode_variant( field_start, TYPE_PROJECTION )

	## Return true if color is present in the buffer, else false
	func color_is_present() -> bool:
		return get_field_offset( VT_COLOR )

	func color() -> Color:
		var field_start: int = get_inline_field_start( VT_COLOR )
		return decode_variant( field_start, TYPE_COLOR )

	func packed_byte_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_BYTE_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Decode and return all elements of packed_byte_array_ as an [PackedByteArray]
	func packed_byte_array_() -> PackedByteArray:
		var array_start: int = get_offset_field_start( VT_PACKED_BYTE_ARRAY_ )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	## Access elements of packed_byte_array_ by [param index]
	func packed_byte_array__at( index: int ) -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_BYTE_ARRAY_ )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes[array_start + index]

	func packed_int32_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_INT32_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Decode and return all elements of packed_int32_array_ as an [PackedInt32Array]
	func packed_int32_array_() -> PackedInt32Array:
		var array_start: int = get_offset_field_start( VT_PACKED_INT32_ARRAY_ )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 4
		return _fb_bytes.slice( array_start, array_end ).to_int32_array()

	## Access elements of packed_int32_array_ by [param index]
	func packed_int32_array__at( index: int ) -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_INT32_ARRAY_ )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes.decode_s32( array_start + index * 4)

	func packed_int64_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_INT64_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Decode and return all elements of packed_int64_array_ as an [PackedInt64Array]
	func packed_int64_array_() -> PackedInt64Array:
		var array_start: int = get_offset_field_start( VT_PACKED_INT64_ARRAY_ )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 8
		return _fb_bytes.slice( array_start, array_end ).to_int64_array()

	## Access elements of packed_int64_array_ by [param index]
	func packed_int64_array__at( index: int ) -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_INT64_ARRAY_ )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes.decode_s64( array_start + index * 8)

	func packed_float32_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_FLOAT32_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Decode and return all elements of packed_float32_array_ as an [PackedFloat32Array]
	func packed_float32_array_() -> PackedFloat32Array:
		var array_start: int = get_offset_field_start( VT_PACKED_FLOAT32_ARRAY_ )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 4
		return _fb_bytes.slice( array_start, array_end ).to_float32_array()

	## Access elements of packed_float32_array_ by [param index]
	func packed_float32_array__at( index: int ) -> float:
		var array_start: int = get_offset_field_start( VT_PACKED_FLOAT32_ARRAY_ )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes.decode_float( array_start + index * 4)

	func packed_float64_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_FLOAT64_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Decode and return all elements of packed_float64_array_ as an [PackedFloat64Array]
	func packed_float64_array_() -> PackedFloat64Array:
		var array_start: int = get_offset_field_start( VT_PACKED_FLOAT64_ARRAY_ )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 8
		return _fb_bytes.slice( array_start, array_end ).to_float64_array()

	## Access elements of packed_float64_array_ by [param index]
	func packed_float64_array__at( index: int ) -> float:
		var array_start: int = get_offset_field_start( VT_PACKED_FLOAT64_ARRAY_ )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes.decode_double( array_start + index * 8)

	func packed_string_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_STRING_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func packed_string_array_() -> PackedStringArray:
		var array_start: int = get_offset_field_start( VT_PACKED_STRING_ARRAY_ )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: PackedStringArray
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var idx: int = array_start + i * 4
			var element_start: int = idx + _fb_bytes.decode_u32( idx )
			array[i] = decode_variant( element_start, TYPE_STRING )
		return array

	func packed_string_array__at( index: int ) -> String:
		var array_start: int = get_offset_field_start( VT_PACKED_STRING_ARRAY_ )
		if not array_start: return ''
		array_start += 4
		var string_start: int = array_start + index * 4
		string_start += _fb_bytes.decode_u32( string_start )
		return decode_variant( string_start, TYPE_STRING )

	func packed_vector2_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_VECTOR2_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func packed_vector2_array_() -> PackedVector2Array:
		var field_start: int = get_offset_field_start( VT_PACKED_VECTOR2_ARRAY_ )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 8 ) \
				.to_vector2_array()

	func packed_vector2_array__at( idx: int ) -> Vector2:
		var field_start: int = get_offset_field_start( VT_PACKED_VECTOR2_ARRAY_ )
		assert(field_start, 'Field "packed_vector2_array_" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 8
		return decode_variant( element_offset, TYPE_VECTOR2 )

	func packed_vector3_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_VECTOR3_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func packed_vector3_array_() -> PackedVector3Array:
		var field_start: int = get_offset_field_start( VT_PACKED_VECTOR3_ARRAY_ )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 12 ) \
				.to_vector3_array()

	func packed_vector3_array__at( idx: int ) -> Vector3:
		var field_start: int = get_offset_field_start( VT_PACKED_VECTOR3_ARRAY_ )
		assert(field_start, 'Field "packed_vector3_array_" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 12
		return decode_variant( element_offset, TYPE_VECTOR3 )

	func packed_color_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_COLOR_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func packed_color_array_() -> PackedColorArray:
		var field_start: int = get_offset_field_start( VT_PACKED_COLOR_ARRAY_ )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 16 ) \
				.to_color_array()

	func packed_color_array__at( idx: int ) -> Color:
		var field_start: int = get_offset_field_start( VT_PACKED_COLOR_ARRAY_ )
		assert(field_start, 'Field "packed_color_array_" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 16
		return decode_variant( element_offset, TYPE_COLOR )

	func packed_vector4_array__size() -> int:
		var array_start: int = get_offset_field_start( VT_PACKED_VECTOR4_ARRAY_ )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func packed_vector4_array_() -> PackedVector4Array:
		var field_start: int = get_offset_field_start( VT_PACKED_VECTOR4_ARRAY_ )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 16 ) \
				.to_vector4_array()

	func packed_vector4_array__at( idx: int ) -> Vector4:
		var field_start: int = get_offset_field_start( VT_PACKED_VECTOR4_ARRAY_ )
		assert(field_start, 'Field "packed_vector4_array_" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 16
		return decode_variant( element_offset, TYPE_VECTOR4 )


## TODO: Write a Doc Comment for the builder
class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_boolean( boolean: bool ) -> void:
		fbb_.add_element_bool_default( RootTable.VT_BOOLEAN, boolean, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_integer( integer: int ) -> void:
		fbb_.add_element_long_default( RootTable.VT_INTEGER, integer, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_floating_point( floating_point: float ) -> void:
		fbb_.add_element_double_default( RootTable.VT_FLOATING_POINT, floating_point, 0.0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_string( string_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_STRING, string_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_vector2( vector2: Vector2 ) -> void:
		fbb_.add_variant( RootTable.VT_VECTOR2, vector2, TYPE_VECTOR2 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_vector2i( vector2i: Vector2i ) -> void:
		fbb_.add_variant( RootTable.VT_VECTOR2I, vector2i, TYPE_VECTOR2I )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_rect2( rect2: Rect2 ) -> void:
		fbb_.add_variant( RootTable.VT_RECT2, rect2, TYPE_RECT2 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_rect2i( rect2i: Rect2i ) -> void:
		fbb_.add_variant( RootTable.VT_RECT2I, rect2i, TYPE_RECT2I )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_vector3( vector3: Vector3 ) -> void:
		fbb_.add_variant( RootTable.VT_VECTOR3, vector3, TYPE_VECTOR3 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_vector3i( vector3i: Vector3i ) -> void:
		fbb_.add_variant( RootTable.VT_VECTOR3I, vector3i, TYPE_VECTOR3I )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_transform2d( transform2d: Transform2D ) -> void:
		fbb_.add_variant( RootTable.VT_TRANSFORM2D, transform2d, TYPE_TRANSFORM2D )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_vector4( vector4: Vector4 ) -> void:
		fbb_.add_variant( RootTable.VT_VECTOR4, vector4, TYPE_VECTOR4 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_vector4i( vector4i: Vector4i ) -> void:
		fbb_.add_variant( RootTable.VT_VECTOR4I, vector4i, TYPE_VECTOR4I )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_plane( plane: Plane ) -> void:
		fbb_.add_variant( RootTable.VT_PLANE, plane, TYPE_PLANE )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_quaternion( quaternion: Quaternion ) -> void:
		fbb_.add_variant( RootTable.VT_QUATERNION, quaternion, TYPE_QUATERNION )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_aabb( aabb: AABB ) -> void:
		fbb_.add_variant( RootTable.VT_AABB, aabb, TYPE_AABB )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_basis( basis: Basis ) -> void:
		fbb_.add_variant( RootTable.VT_BASIS, basis, TYPE_BASIS )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_transform3d( transform3d: Transform3D ) -> void:
		fbb_.add_variant( RootTable.VT_TRANSFORM3D, transform3d, TYPE_TRANSFORM3D )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_projection( projection: Projection ) -> void:
		fbb_.add_variant( RootTable.VT_PROJECTION, projection, TYPE_PROJECTION )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_color( color: Color ) -> void:
		fbb_.add_variant( RootTable.VT_COLOR, color, TYPE_COLOR )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_byte_array_( packed_byte_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_BYTE_ARRAY_, packed_byte_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_int32_array_( packed_int32_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_INT32_ARRAY_, packed_int32_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_int64_array_( packed_int64_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_INT64_ARRAY_, packed_int64_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_float32_array_( packed_float32_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_FLOAT32_ARRAY_, packed_float32_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_float64_array_( packed_float64_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_FLOAT64_ARRAY_, packed_float64_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_string_array_( packed_string_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_STRING_ARRAY_, packed_string_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_vector2_array_( packed_vector2_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_VECTOR2_ARRAY_, packed_vector2_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_vector3_array_( packed_vector3_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_VECTOR3_ARRAY_, packed_vector3_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_color_array_( packed_color_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_COLOR_ARRAY_, packed_color_array__offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_packed_vector4_array_( packed_vector4_array__offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_PACKED_VECTOR4_ARRAY_, packed_vector4_array__offset )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_RootTable( _fbb: FlatBufferBuilder,
		boolean: bool,
		integer: int,
		floating_point: float,
		string: int,
		vector2: Vector2,
		vector2i: Vector2i,
		rect2: Rect2,
		rect2i: Rect2i,
		vector3: Vector3,
		vector3i: Vector3i,
		transform2d: Transform2D,
		vector4: Vector4,
		vector4i: Vector4i,
		plane: Plane,
		quaternion: Quaternion,
		aabb: AABB,
		basis: Basis,
		transform3d: Transform3D,
		projection: Projection,
		color: Color,
		packed_byte_array_: int,
		packed_int32_array_: int,
		packed_int64_array_: int,
		packed_float32_array_: int,
		packed_float64_array_: int,
		packed_string_array_: int,
		packed_vector2_array_: int,
		packed_vector3_array_: int,
		packed_color_array_: int,
		packed_vector4_array_: int ) -> int :
	var builder: RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_floating_point( floating_point );
	builder.add_integer( integer );
	builder.add_packed_vector4_array_( packed_vector4_array_ );
	builder.add_packed_color_array_( packed_color_array_ );
	builder.add_packed_vector3_array_( packed_vector3_array_ );
	builder.add_packed_vector2_array_( packed_vector2_array_ );
	builder.add_packed_string_array_( packed_string_array_ );
	builder.add_packed_float64_array_( packed_float64_array_ );
	builder.add_packed_float32_array_( packed_float32_array_ );
	builder.add_packed_int64_array_( packed_int64_array_ );
	builder.add_packed_int32_array_( packed_int32_array_ );
	builder.add_packed_byte_array_( packed_byte_array_ );
	builder.add_color( color );
	builder.add_projection( projection );
	builder.add_transform3d( transform3d );
	builder.add_basis( basis );
	builder.add_aabb( aabb );
	builder.add_quaternion( quaternion );
	builder.add_plane( plane );
	builder.add_vector4i( vector4i );
	builder.add_vector4( vector4 );
	builder.add_transform2d( transform2d );
	builder.add_vector3i( vector3i );
	builder.add_vector3( vector3 );
	builder.add_rect2i( rect2i );
	builder.add_rect2( rect2 );
	builder.add_vector2i( vector2i );
	builder.add_vector2( vector2 );
	builder.add_string( string );
	builder.add_boolean( boolean );
	return builder.finish();

## TODO: create a doc comment for the get_RootTable function
static func get_RootTable( _bytes: PackedByteArray ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _bytes.decode_u32(0))

