# automatically generated by the FlatBuffers compiler, do not modify

static func GetRoot( _bytes : PackedByteArray ) -> RootTable:
	return GetRootTable( _bytes, _bytes.decode_u32(0) )

static func GetRootTable( _bytes : PackedByteArray, _start : int = 0 ) -> RootTable:
	if _bytes.is_empty(): return null
	var new_RootTable = RootTable.new()
	new_RootTable.start = _start
	new_RootTable.bytes = _bytes
	return new_RootTable


class RootTable extends FlatBuffer:
	enum vtable{
		VT_MY_STRING = 4
	}

	func my_string_is_present() -> bool:
		return get_field_offset( vtable.VT_MY_STRING )

	func my_string() -> String:
		var field_start = get_field_start( vtable.VT_MY_STRING )
		if not field_start: return ''
		return decode_String( field_start )


class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_my_string( my_string_offset : int ) -> void:
		fbb_.add_offset( RootTable.vtable.VT_MY_STRING, my_string_offset )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateRootTable( _fbb : FlatBufferBuilder,
		my_string : int ) -> int :
	var builder = RootTableBuilder.new( _fbb );
	builder.add_my_string( my_string );
	return builder.finish();

