# automatically generated by the FlatBuffers compiler, do not modify

static func GetRoot( _bytes : PackedByteArray ) -> RootTable:
	return GetRootTable( _bytes, _bytes.decode_u32(0) )

static func GetMyStruct( _bytes : PackedByteArray, _start : int ):
	return MyStruct.new( _bytes, _start )

class MyStruct extends FlatBuffer:
	func _init( bytes_ : PackedByteArray = [], start_ : int = 0) -> void:
		if bytes_.is_empty(): 
			var data = PackedByteArray()
			data.resize( 8 )
			bytes = data
			start = 0
		else: bytes = bytes_; start = start_

	# x : int
	var x : int :
		get(): return bytes.decode_s32(start + 0)
		set( v ):
			var data = bytes
			data.encode_s32(start + 0, v )
			bytes = data

	# y : float
	var y : float :
		get(): return bytes.decode_float(start + 4)
		set( v ):
			var data = bytes
			data.encode_float(start + 4, v )
			bytes = data


static func GetRootTable( _bytes : PackedByteArray, _start : int = 0 ) -> RootTable:
	if _bytes.is_empty(): return null
	var new_RootTable = RootTable.new()
	new_RootTable.start = _start
	new_RootTable.bytes = _bytes
	return new_RootTable


class RootTable extends FlatBuffer:
	enum vtable{
		VT_MY_STRUCT = 4,
		VT_BUILTIN_STRUCT = 6
	}

	func my_struct_is_present() -> bool:
		return get_field_offset( vtable.VT_MY_STRUCT )

	func my_struct() -> MyStruct:
		var field_offset = get_field_offset( vtable.VT_MY_STRUCT )
		if not field_offset: return null
		return parent.GetMyStruct( bytes, start + field_offset )

	func builtin_struct_is_present() -> bool:
		return get_field_offset( vtable.VT_BUILTIN_STRUCT )

	func builtin_struct() -> Vector3i:
		return GetVector3i( vtable.VT_BUILTIN_STRUCT )


class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_my_struct( my_struct : MyStruct ) -> void:
		fbb_.add_bytes( RootTable.vtable.VT_MY_STRUCT, my_struct.bytes ) 

	func add_builtin_struct( builtin_struct : Vector3i ) -> void:
		fbb_.add_Vector3i( RootTable.vtable.VT_BUILTIN_STRUCT, builtin_struct )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateRootTable( _fbb : FlatBufferBuilder,
		my_struct : MyStruct,
		builtin_struct : Vector3i ) -> int :
	var builder = RootTableBuilder.new( _fbb );
	builder.add_builtin_struct( builtin_struct );
	builder.add_my_struct( my_struct );
	return builder.finish();

