# automatically generated by the FlatBuffers compiler, do not modify

static func GetRoot( _bytes : PackedByteArray ) -> Monster:
	return GetMonster( _bytes, _bytes.decode_u32(0) )

enum Color_ {
	RED = 0,
	GREEN = 1,
	BLUE = 2
}

enum Equipment {
	NONE = 0,
	WEAPON = 1
}

static func GetVec3( _bytes : PackedByteArray, _start : int ):
	return Vec3.new( _bytes, _start )

class Vec3 extends FlatBuffer:
	func _init( bytes_ : PackedByteArray = [], start_ : int = 0) -> void:
		if bytes_.is_empty(): 
			var data = PackedByteArray()
			data.resize( 12 )
			bytes = data
			start = 0
		else: bytes = bytes_; start = start_

	# x : float
	var x : float :
		get(): return bytes.decode_float(start + 0)
		set( v ):
			var data = bytes
			data.encode_float(start + 0, v )
			bytes = data

	# y : float
	var y : float :
		get(): return bytes.decode_float(start + 4)
		set( v ):
			var data = bytes
			data.encode_float(start + 4, v )
			bytes = data

	# z : float
	var z : float :
		get(): return bytes.decode_float(start + 8)
		set( v ):
			var data = bytes
			data.encode_float(start + 8, v )
			bytes = data


static func GetMonster( _bytes : PackedByteArray, _start : int = 0 ) -> Monster:
	if _bytes.is_empty(): return null
	var new_Monster = Monster.new()
	new_Monster.start = _start
	new_Monster.bytes = _bytes
	return new_Monster


class Monster extends FlatBuffer:
	enum vtable{
		VT_POS = 4,
		VT_MANA = 6,
		VT_HP = 8,
		VT_NAME = 10,
		VT_INVENTORY = 14,
		VT_COLOR = 16,
		VT_WEAPONS = 18,
		VT_EQUIPPED_TYPE = 20,
		VT_EQUIPPED = 22,
		VT_PATH = 24
	}

	func pos_is_present() -> bool:
		return get_field_offset( vtable.VT_POS )

	func pos() -> Vec3:
		var field_offset = get_field_offset( vtable.VT_POS )
		if not field_offset: return null
		return parent.GetVec3( bytes, start + field_offset )

	func mana_is_present() -> bool:
		return get_field_offset( vtable.VT_MANA )

	func mana() -> int:
		var foffset = get_field_offset( vtable.VT_MANA )
		if not foffset: return 150
		return bytes.decode_s16( start + foffset )

	func hp_is_present() -> bool:
		return get_field_offset( vtable.VT_HP )

	func hp() -> int:
		var foffset = get_field_offset( vtable.VT_HP )
		if not foffset: return 100
		return bytes.decode_s16( start + foffset )

	func name_is_present() -> bool:
		return get_field_offset( vtable.VT_NAME )

	func name() -> String:
		var field_start = get_field_start( vtable.VT_NAME )
		if not field_start: return ''
		return decode_String( field_start )

	# field:'friendly' is deprecated

	func inventory_is_present() -> bool:
		return get_field_offset( vtable.VT_INVENTORY )

	func inventory_size() -> int:
		var array_start = get_field_start( vtable.VT_INVENTORY )
		if not array_start: return 0
		return bytes.decode_u32( array_start )

	func inventory() -> PackedByteArray:
		var array_start = get_field_start( vtable.VT_INVENTORY )
		if not array_start: return []
		var array_size = bytes.decode_u32( array_start )
		array_start += 4
		return bytes.slice( array_start, array_start + array_size )

	func inventory_at( index : int ) -> int:
		var array_start = get_field_start( vtable.VT_INVENTORY )
		if not array_start: return 0
		array_start += 4
		return bytes[array_start + index]

	func color_is_present() -> bool:
		return get_field_offset( vtable.VT_COLOR )

	func color() -> Color_:
		var foffset = get_field_offset( vtable.VT_COLOR )
		if not foffset: return 2 as Color_
		return bytes.decode_s8( start + foffset ) as Color_

	func weapons_is_present() -> bool:
		return get_field_offset( vtable.VT_WEAPONS )

	func weapons_size() -> int:
		var array_start = get_field_start( vtable.VT_WEAPONS )
		if not array_start: return 0
		return bytes.decode_u32( array_start )

	func weapons() -> Array:
		var array_start = get_field_start( vtable.VT_WEAPONS )
		if not array_start: return []
		var array_size = bytes.decode_u32( array_start )
		array_start += 4
		var array : Array; array.resize( array_size )
		for i in array_size:
			var pos = array_start + i * 4
			array[i] = parent.GetWeapon( bytes, pos + bytes.decode_u32( pos ) )
		return array

	func equipped_type_is_present() -> bool:
		return get_field_offset( vtable.VT_EQUIPPED_TYPE )

	func equipped_type() -> Equipment:
		var foffset = get_field_offset( vtable.VT_EQUIPPED_TYPE )
		if not foffset: return 0 as Equipment
		return bytes.decode_u8( start + foffset ) as Equipment

	func equipped_is_present() -> bool:
		return get_field_offset( vtable.VT_EQUIPPED )

	func equipped() -> Variant:
		var field_start = get_field_start( vtable.VT_EQUIPPED )
		if not field_start: return null
		match( equipped_type() ):
			Equipment.WEAPON:
				return parent.GetWeapon( bytes, field_start )
			_: pass
		return null

	func path_is_present() -> bool:
		return get_field_offset( vtable.VT_PATH )

	func path_size() -> int:
		var array_start = get_field_start( vtable.VT_PATH )
		if not array_start: return 0
		return bytes.decode_u32( array_start )

	func path() -> Array:
		var array_start = get_field_start( vtable.VT_PATH )
		if not array_start: return []
		var array_size = bytes.decode_u32( array_start )
		array_start += 4
		# TODO Vector of Structs
		return []


class MonsterBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_pos( pos : Vec3 ) -> void:
		fbb_.add_bytes( Monster.vtable.VT_POS, pos.bytes ) 

	func add_mana( mana : int ) -> void:
		fbb_.add_element_short_default( Monster.vtable.VT_MANA, mana, 150 )

	func add_hp( hp : int ) -> void:
		fbb_.add_element_short_default( Monster.vtable.VT_HP, hp, 100 )

	func add_name( name_offset : int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_NAME, name_offset )

	func add_inventory( inventory_offset : int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_INVENTORY, inventory_offset )

	func add_color( color : Color_ ) -> void:
		fbb_.add_element_byte_default( Monster.vtable.VT_COLOR, color, 2 )

	func add_weapons( weapons_offset : int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_WEAPONS, weapons_offset )

	func add_equipped_type( equipped_type : Equipment ) -> void:
		fbb_.add_element_ubyte_default( Monster.vtable.VT_EQUIPPED_TYPE, equipped_type, 0 )

	func add_equipped( equipped_offset : int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_EQUIPPED, equipped_offset )

	func add_path( path_offset : int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_PATH, path_offset )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateMonster( _fbb : FlatBufferBuilder,
		pos : Vec3,
		mana : int,
		hp : int,
		name : int,
		inventory : int,
		color : Color_,
		weapons : int,
		equipped_type : Equipment,
		equipped : int,
		path : int ) -> int :
	var builder = MonsterBuilder.new( _fbb );
	builder.add_path( path );
	builder.add_equipped( equipped );
	builder.add_weapons( weapons );
	builder.add_inventory( inventory );
	builder.add_name( name );
	builder.add_pos( pos );
	builder.add_hp( hp );
	builder.add_mana( mana );
	builder.add_equipped_type( equipped_type );
	builder.add_color( color );
	return builder.finish();

static func GetWeapon( _bytes : PackedByteArray, _start : int  ) -> Weapon:
	if _bytes.is_empty(): return null
	var new_Weapon = Weapon.new()
	new_Weapon.start = _start
	new_Weapon.bytes = _bytes
	return new_Weapon


class Weapon extends FlatBuffer:
	enum vtable{
		VT_NAME = 4,
		VT_DAMAGE = 6
	}

	func name_is_present() -> bool:
		return get_field_offset( vtable.VT_NAME )

	func name() -> String:
		var field_start = get_field_start( vtable.VT_NAME )
		if not field_start: return ''
		return decode_String( field_start )

	func damage_is_present() -> bool:
		return get_field_offset( vtable.VT_DAMAGE )

	func damage() -> int:
		var foffset = get_field_offset( vtable.VT_DAMAGE )
		if not foffset: return 0
		return bytes.decode_s16( start + foffset )


class WeaponBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_name( name_offset : int ) -> void:
		fbb_.add_offset( Weapon.vtable.VT_NAME, name_offset )

	func add_damage( damage : int ) -> void:
		fbb_.add_element_short_default( Weapon.vtable.VT_DAMAGE, damage, 0 )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateWeapon( _fbb : FlatBufferBuilder,
		name : int,
		damage : int ) -> int :
	var builder = WeaponBuilder.new( _fbb );
	builder.add_name( name );
	builder.add_damage( damage );
	return builder.finish();

