# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class Attribute extends FlatBuffer:
	enum vtable{

	}

	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	# Presence Functions
	# field:'deprecated_field' is deprecated


class AttributeBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;


static func create_Attribute( _fbb: FlatBufferBuilder,
		 ) -> int :
	var builder: AttributeBuilder = AttributeBuilder.new( _fbb );
	return builder.finish();

static func get_Attribute( _bytes: PackedByteArray ) -> Attribute:
	assert(not _bytes.is_empty())
	return Attribute.new(_bytes, _bytes.decode_u32(0))
