# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class Attribute extends FlatBuffer:
	enum {
		VT_DEPRECATED_FIELD = 4
	}

	## Initialize the STRUCT_NAME with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the STRUCT_NAME data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_end_table(verifier)
		)


## Builder class for Attribute
class AttributeBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Finish building the Attribute table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a Attribute table in one go using the provided [param _fbb]
static func create_Attribute( _fbb: FlatBufferBuilder,
		 ) -> int :
	var builder: AttributeBuilder = AttributeBuilder.new( _fbb );
	return builder.finish();

## Get the Attribute from the provided [param _bytes]
static func get_Attribute( _bytes: PackedByteArray ) -> Attribute:
	assert(not _bytes.is_empty())
	return Attribute.new(_bytes, _bytes.decode_u32(0))

