# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

## Enum Variations
enum Enum1 {
	NONE = 0
}

enum Enum2 {
	NONE = 0
}

enum Enum3 {
	NONE = 0
}

enum Enum4 {
	NONE = 0
}

enum Fruit {
	APPLES = 0,
	BANNAS = 1,
	ORANGES = 1,
	MORE_BANNANAS = 2,
	EVEN_MORE_BANANNAS = 4
}

class TableDecl extends FlatBuffer:
	enum {
		VT_SCALAR_BOOL = 4,
		VT_SCALAR_INT = 6,
		VT_SCALAR_FLOAT = 8,
		VT_IDENT5 = 10
	}

	## Initialize the STRUCT_NAME with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the STRUCT_NAME data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_field_u8(verifier, VT_SCALAR_BOOL, 1)
			and verify_field_s32(verifier, VT_SCALAR_INT, 4)
			and verify_field_float(verifier, VT_SCALAR_FLOAT, 4)
			and verify_offset(verifier, VT_IDENT5)
			and verify_vector_u32(verifier, VT_IDENT5)
			and verify_end_table(verifier)
		)

	## Return true if scalar_bool is present in the buffer, else false
	func scalar_bool_is_present() -> bool:
		return get_field_offset( VT_SCALAR_BOOL )

	func scalar_bool() -> bool:
		var field_start: int = get_inline_field_start( VT_SCALAR_BOOL )
		if not field_start: return 0
		return _fb_bytes.decode_u8( field_start )

	## Return true if scalar_int is present in the buffer, else false
	func scalar_int_is_present() -> bool:
		return get_field_offset( VT_SCALAR_INT )

	func scalar_int() -> int:
		var field_start: int = get_inline_field_start( VT_SCALAR_INT )
		if not field_start: return 32
		return _fb_bytes.decode_s32( field_start )

	## Return true if scalar_float is present in the buffer, else false
	func scalar_float_is_present() -> bool:
		return get_field_offset( VT_SCALAR_FLOAT )

	func scalar_float() -> float:
		var field_start: int = get_inline_field_start( VT_SCALAR_FLOAT )
		if not field_start: return 5.3
		return _fb_bytes.decode_float( field_start )

	func ident5_size() -> int:
		var array_start: int = get_offset_field_start( VT_IDENT5 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Access elements of ident5 by [param index]
	func ident5_at( index: int ) -> int:
		var array_start: int = get_offset_field_start( VT_IDENT5 )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes.decode_u32( array_start + index * 4)

	## Decode and return all elements of ident5 as an [Array]
	func ident5() -> Array:
		var array_start: int = get_offset_field_start( VT_IDENT5 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_u32( array_start + i * 4)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array


## Builder class for TableDecl
class TableDeclBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Add the scalar_bool field to the TableDecl table
	func add_scalar_bool( scalar_bool: bool ) -> void:
		fbb_.add_element_bool_default( TableDecl.VT_SCALAR_BOOL, scalar_bool, 0 )

	## Add the scalar_int field to the TableDecl table
	func add_scalar_int( scalar_int: int ) -> void:
		fbb_.add_element_int_default( TableDecl.VT_SCALAR_INT, scalar_int, 32 )

	## Add the scalar_float field to the TableDecl table
	func add_scalar_float( scalar_float: float ) -> void:
		fbb_.add_element_float_default( TableDecl.VT_SCALAR_FLOAT, scalar_float, 5.3 )

	## Add the ident5 field to the TableDecl table
	func add_ident5( ident5_offset: int ) -> void:
		fbb_.add_offset( TableDecl.VT_IDENT5, ident5_offset )

	## Finish building the TableDecl table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a TableDecl table in one go using the provided [param _fbb]
static func create_TableDecl( _fbb: FlatBufferBuilder,
		scalar_bool: bool,
		scalar_int: int,
		scalar_float: float,
		ident5: int ) -> int :
	var builder: TableDeclBuilder = TableDeclBuilder.new( _fbb );
	builder.add_ident5( ident5 );
	builder.add_scalar_float( scalar_float );
	builder.add_scalar_int( scalar_int );
	builder.add_scalar_bool( scalar_bool );
	return builder.finish();

