# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

# Enum Variations
enum Enum1 {
	NONE = 0
}

enum Enum2 {
	NONE = 0
}

enum Enum3 {
	NONE = 0
}

enum Enum4 {
	NONE = 0
}

enum Fruit {
	APPLES = 0,
	BANNAS = 1,
	ORANGES = 1,
	MORE_BANNANAS = 2,
	EVEN_MORE_BANANNAS = 4
}

class TableDecl extends FlatBuffer:
	enum vtable{
		VT_SCALAR_BOOL = 4,
		VT_SCALAR_INT = 6,
		VT_SCALAR_FLOAT = 8,
		VT_IDENT5 = 10
	}

	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	# Presence Functions
	func scalar_bool_is_present() -> bool:
		return get_field_offset( vtable.VT_SCALAR_BOOL )

	func scalar_int_is_present() -> bool:
		return get_field_offset( vtable.VT_SCALAR_INT )

	func scalar_float_is_present() -> bool:
		return get_field_offset( vtable.VT_SCALAR_FLOAT )

	func ident5_is_present() -> bool:
		return get_field_offset( vtable.VT_IDENT5 )

	# [================[ scalar_bool ]================]
	func scalar_bool() -> bool:
		var foffset: int = get_field_offset( vtable.VT_SCALAR_BOOL )
		if not foffset: return 0
		return _fb_bytes.decode_u8( _fb_start + foffset )

	# [================[ scalar_int ]================]
	func scalar_int() -> int:
		var foffset: int = get_field_offset( vtable.VT_SCALAR_INT )
		if not foffset: return 32
		return _fb_bytes.decode_s32( _fb_start + foffset )

	# [================[ scalar_float ]================]
	func scalar_float() -> float:
		var foffset: int = get_field_offset( vtable.VT_SCALAR_FLOAT )
		if not foffset: return 5.3
		return _fb_bytes.decode_float( _fb_start + foffset )

	# [================[ ident5 ]================]
	func ident5_size() -> int:
		var array_start: int = get_field_start( vtable.VT_IDENT5 )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func ident5() -> Array:
		var array_start: int = get_field_start( vtable.VT_IDENT5 )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _fb_bytes.decode_u32( array_start + i * 4)
		# To return packed array types, the scalar elements have to be of an appropriate type.
		return array

	func ident5_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_IDENT5 )
		if not array_start: return 0
		array_start += 4
		return _fb_bytes.decode_u32( array_start + index * 4)


class TableDeclBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_scalar_bool( scalar_bool: bool ) -> void:
		fbb_.add_element_bool_default( TableDecl.vtable.VT_SCALAR_BOOL, scalar_bool, 0 )

	func add_scalar_int( scalar_int: int ) -> void:
		fbb_.add_element_int_default( TableDecl.vtable.VT_SCALAR_INT, scalar_int, 32 )

	func add_scalar_float( scalar_float: float ) -> void:
		fbb_.add_element_float_default( TableDecl.vtable.VT_SCALAR_FLOAT, scalar_float, 5.3 )

	func add_ident5( ident5_offset: int ) -> void:
		fbb_.add_offset( TableDecl.vtable.VT_IDENT5, ident5_offset )

	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;


static func create_TableDecl( _fbb: FlatBufferBuilder,
		scalar_bool: bool,
		scalar_int: int,
		scalar_float: float,
		ident5: int ) -> int :
	var builder: TableDeclBuilder = TableDeclBuilder.new( _fbb );
	builder.add_ident5( ident5 );
	builder.add_scalar_float( scalar_float );
	builder.add_scalar_int( scalar_int );
	builder.add_scalar_bool( scalar_bool );
	return builder.finish();

