# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

const minimum_schema = preload('minimum_generated.gd')
const Minimum = minimum_schema.Minimum

class RootTable extends FlatBuffer:
	const _minimum_schema = preload( 'minimum_generated.gd' )

	enum {
		VT_EXTERNAL = 4,
		VT_EXTERNAL_ARRAY = 6
	}

	## Initialize the STRUCT_NAME with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the STRUCT_NAME data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_offset(verifier, VT_EXTERNAL)
			and external().verify(verifier)
			and verify_offset(verifier, VT_EXTERNAL_ARRAY)
			and verify_vector_u32(verifier, VT_EXTERNAL_ARRAY)
			and external_array_verify(verifier)
			and verify_end_table(verifier)
		)

	## Return true if external is present in the buffer, else false
	func external_is_present() -> bool:
		return get_field_offset( VT_EXTERNAL )

	func external() -> _minimum_schema.Minimum:
		var field_start: int = get_offset_field_start( VT_EXTERNAL )
		if not field_start: return null
		return _minimum_schema.Minimum.new( _fb_bytes, field_start )

	## Return true if external_array is present in the buffer, else false
	func external_array_is_present() -> bool:
		return get_field_offset( VT_EXTERNAL_ARRAY )

	func external_array_verify(verifier:FlatBufferVerifier) -> bool:
		var tmp := _minimum_schema.Minimum.new()
		for i in external_array_size():
			if not external_array_at(i, tmp).verify(verifier):
				return false
		return true

	func external_array_size() -> int:
		var array_start: int = get_offset_field_start( VT_EXTERNAL_ARRAY )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func external_array_at( idx: int, into: Minimum = null ) -> Minimum:
		var field_start: int = get_offset_field_start( VT_EXTERNAL_ARRAY )
		assert(field_start, 'Field "external_array" is not present in buffer' )

		# The field is a vector of table, so the inline data is a vector of
		# offsets to the element location.

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_pos: int = array_start + idx * 4
		var element_offset: int = _fb_bytes.decode_u32(element_pos)
		if into:
			into.assign_buffer(_fb_bytes, element_pos + element_offset)
			return into
		return _minimum_schema.Minimum.new( _fb_bytes, element_pos + element_offset )

	func external_array() -> Array:
		var array_start: int = get_offset_field_start( VT_EXTERNAL_ARRAY )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var p: int = array_start + i * 4
			array[i] = _minimum_schema.Minimum.new( _fb_bytes, p + _fb_bytes.decode_u32( p ) )
		return array


## Builder class for RootTable
class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Add the external field to the RootTable table
	func add_external( external_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_EXTERNAL, external_offset )

	## Add the external_array field to the RootTable table
	func add_external_array( external_array_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_EXTERNAL_ARRAY, external_array_offset )

	## Finish building the RootTable table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a RootTable table in one go using the provided [param _fbb]
static func create_RootTable( _fbb: FlatBufferBuilder,
		external: int,
		external_array: int ) -> int :
	var builder: RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_external_array( external_array );
	builder.add_external( external );
	return builder.finish();

## Get the RootTable from the provided [param _bytes]
static func get_RootTable( _bytes: PackedByteArray ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _bytes.decode_u32(0))

