# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

const minimum_schema = preload('minimum_generated.gd')
const Minimum = minimum_schema.Minimum

class RootTable extends FlatBuffer:
	const _minimum_schema = preload( 'minimum_generated.gd' )

	enum {
		VT_EXTERNAL = 4,
		VT_EXTERNAL_ARRAY = 6
	}

	## TODO: create a useful doc comment for the init function
	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	## Return true if external is present in the buffer, else false
	func external_is_present() -> bool:
		return get_field_offset( VT_EXTERNAL )

	func external() -> _minimum_schema.Minimum:
		var field_start: int = get_offset_field_start( VT_EXTERNAL )
		if not field_start: return null
		return _minimum_schema.Minimum.new( _fb_bytes, field_start )

	func external_array_size() -> int:
		var array_start: int = get_offset_field_start( VT_EXTERNAL_ARRAY )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func external_array() -> Array:
		var array_start: int = get_offset_field_start( VT_EXTERNAL_ARRAY )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var p: int = array_start + i * 4
			array[i] = _minimum_schema.Minimum.new( _fb_bytes, p + _fb_bytes.decode_u32( p ) )
		return array

	func external_array_at( idx: int, into: Minimum = null ) -> Minimum:
		var field_start: int = get_offset_field_start( VT_EXTERNAL_ARRAY )
		assert(field_start, 'Field "external_array" is not present in buffer' )

		# The field is a vector of table, so the inline data is a vector of
		# offsets to the element location.

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_pos: int = array_start + idx * 4
		var element_offset: int = _fb_bytes.decode_u32(element_pos)
		if into:
			into._fb_bytes = _fb_bytes
			into._fb_start = element_pos + element_offset
			return into
		return _minimum_schema.Minimum.new( _fb_bytes, element_pos + element_offset )


## TODO: Write a Doc Comment for the builder
class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_external( external_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_EXTERNAL, external_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_external_array( external_array_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_EXTERNAL_ARRAY, external_array_offset )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_RootTable( _fbb: FlatBufferBuilder,
		external: int,
		external_array: int ) -> int :
	var builder: RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_external_array( external_array );
	builder.add_external( external );
	return builder.finish();

## TODO: create a doc comment for the get_RootTable function
static func get_RootTable( _bytes: PackedByteArray ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _bytes.decode_u32(0))

