# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class Minimum extends FlatBuffer:
	enum {
		VT_MY_FIELD = 4
	}

	## Initialize the STRUCT_NAME with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the STRUCT_NAME data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_field_s32(verifier, VT_MY_FIELD, 4)
			and verify_end_table(verifier)
		)

	## Return true if my_field is present in the buffer, else false
	func my_field_is_present() -> bool:
		return get_field_offset( VT_MY_FIELD )

	func my_field() -> int:
		var field_start: int = get_inline_field_start( VT_MY_FIELD )
		if not field_start: return 0
		return _fb_bytes.decode_s32( field_start )


## Builder class for Minimum
class MinimumBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Add the my_field field to the Minimum table
	func add_my_field( my_field: int ) -> void:
		fbb_.add_element_int_default( Minimum.VT_MY_FIELD, my_field, 0 )

	## Finish building the Minimum table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a Minimum table in one go using the provided [param _fbb]
static func create_Minimum( _fbb: FlatBufferBuilder,
		my_field: int ) -> int :
	var builder: MinimumBuilder = MinimumBuilder.new( _fbb );
	builder.add_my_field( my_field );
	return builder.finish();

## Get the Minimum from the provided [param _bytes]
static func get_Minimum( _bytes: PackedByteArray ) -> Minimum:
	assert(not _bytes.is_empty())
	return Minimum.new(_bytes, _bytes.decode_u32(0))

