# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class RootTable extends FlatBuffer:
	enum {
		VT_F_BOOL = 4,
		VT_F_BYTE = 6,
		VT_F_UBYTE = 8,
		VT_F_SHORT = 10,
		VT_F_USHORT = 12,
		VT_F_INT = 14,
		VT_F_UINT = 16,
		VT_F_LONG = 18,
		VT_F_ULONG = 20,
		VT_F_FLOAT = 22,
		VT_F_DOUBLE = 24
	}

	## TODO: create a useful doc comment for the init function
	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	## Return true if f_bool is present in the buffer, else false
	func f_bool_is_present() -> bool:
		return get_field_offset( VT_F_BOOL )

	func f_bool() -> bool:
		var field_start: int = get_inline_field_start( VT_F_BOOL )
		if not field_start: return 0
		return _fb_bytes.decode_u8( field_start )

	## Return true if f_byte is present in the buffer, else false
	func f_byte_is_present() -> bool:
		return get_field_offset( VT_F_BYTE )

	func f_byte() -> int:
		var field_start: int = get_inline_field_start( VT_F_BYTE )
		if not field_start: return 0
		return _fb_bytes.decode_s8( field_start )

	## Return true if f_ubyte is present in the buffer, else false
	func f_ubyte_is_present() -> bool:
		return get_field_offset( VT_F_UBYTE )

	func f_ubyte() -> int:
		var field_start: int = get_inline_field_start( VT_F_UBYTE )
		if not field_start: return 0
		return _fb_bytes.decode_u8( field_start )

	## Return true if f_short is present in the buffer, else false
	func f_short_is_present() -> bool:
		return get_field_offset( VT_F_SHORT )

	func f_short() -> int:
		var field_start: int = get_inline_field_start( VT_F_SHORT )
		if not field_start: return 0
		return _fb_bytes.decode_s16( field_start )

	## Return true if f_ushort is present in the buffer, else false
	func f_ushort_is_present() -> bool:
		return get_field_offset( VT_F_USHORT )

	func f_ushort() -> int:
		var field_start: int = get_inline_field_start( VT_F_USHORT )
		if not field_start: return 0
		return _fb_bytes.decode_u16( field_start )

	## Return true if f_int is present in the buffer, else false
	func f_int_is_present() -> bool:
		return get_field_offset( VT_F_INT )

	func f_int() -> int:
		var field_start: int = get_inline_field_start( VT_F_INT )
		if not field_start: return 0
		return _fb_bytes.decode_s32( field_start )

	## Return true if f_uint is present in the buffer, else false
	func f_uint_is_present() -> bool:
		return get_field_offset( VT_F_UINT )

	func f_uint() -> int:
		var field_start: int = get_inline_field_start( VT_F_UINT )
		if not field_start: return 0
		return _fb_bytes.decode_u32( field_start )

	## Return true if f_long is present in the buffer, else false
	func f_long_is_present() -> bool:
		return get_field_offset( VT_F_LONG )

	func f_long() -> int:
		var field_start: int = get_inline_field_start( VT_F_LONG )
		if not field_start: return 0
		return _fb_bytes.decode_s64( field_start )

	## Return true if f_ulong is present in the buffer, else false
	func f_ulong_is_present() -> bool:
		return get_field_offset( VT_F_ULONG )

	func f_ulong() -> int:
		var field_start: int = get_inline_field_start( VT_F_ULONG )
		if not field_start: return 0
		return _fb_bytes.decode_u64( field_start )

	## Return true if f_float is present in the buffer, else false
	func f_float_is_present() -> bool:
		return get_field_offset( VT_F_FLOAT )

	func f_float() -> float:
		var field_start: int = get_inline_field_start( VT_F_FLOAT )
		if not field_start: return 0.0
		return _fb_bytes.decode_float( field_start )

	## Return true if f_double is present in the buffer, else false
	func f_double_is_present() -> bool:
		return get_field_offset( VT_F_DOUBLE )

	func f_double() -> float:
		var field_start: int = get_inline_field_start( VT_F_DOUBLE )
		if not field_start: return 0.0
		return _fb_bytes.decode_double( field_start )


## TODO: Write a Doc Comment for the builder
class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_bool( f_bool: bool ) -> void:
		fbb_.add_element_bool_default( RootTable.VT_F_BOOL, f_bool, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_byte( f_byte: int ) -> void:
		fbb_.add_element_byte_default( RootTable.VT_F_BYTE, f_byte, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_ubyte( f_ubyte: int ) -> void:
		fbb_.add_element_ubyte_default( RootTable.VT_F_UBYTE, f_ubyte, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_short( f_short: int ) -> void:
		fbb_.add_element_short_default( RootTable.VT_F_SHORT, f_short, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_ushort( f_ushort: int ) -> void:
		fbb_.add_element_ushort_default( RootTable.VT_F_USHORT, f_ushort, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_int( f_int: int ) -> void:
		fbb_.add_element_int_default( RootTable.VT_F_INT, f_int, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_uint( f_uint: int ) -> void:
		fbb_.add_element_uint_default( RootTable.VT_F_UINT, f_uint, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_long( f_long: int ) -> void:
		fbb_.add_element_long_default( RootTable.VT_F_LONG, f_long, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_ulong( f_ulong: int ) -> void:
		fbb_.add_element_ulong_default( RootTable.VT_F_ULONG, f_ulong, 0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_float( f_float: float ) -> void:
		fbb_.add_element_float_default( RootTable.VT_F_FLOAT, f_float, 0.0 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_f_double( f_double: float ) -> void:
		fbb_.add_element_double_default( RootTable.VT_F_DOUBLE, f_double, 0.0 )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_RootTable( _fbb: FlatBufferBuilder,
		f_bool: bool,
		f_byte: int,
		f_ubyte: int,
		f_short: int,
		f_ushort: int,
		f_int: int,
		f_uint: int,
		f_long: int,
		f_ulong: int,
		f_float: float,
		f_double: float ) -> int :
	var builder: RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_f_double( f_double );
	builder.add_f_ulong( f_ulong );
	builder.add_f_long( f_long );
	builder.add_f_float( f_float );
	builder.add_f_uint( f_uint );
	builder.add_f_int( f_int );
	builder.add_f_ushort( f_ushort );
	builder.add_f_short( f_short );
	builder.add_f_ubyte( f_ubyte );
	builder.add_f_byte( f_byte );
	builder.add_f_bool( f_bool );
	return builder.finish();

## TODO: create a doc comment for the get_RootTable function
static func get_RootTable( _bytes: PackedByteArray ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _bytes.decode_u32(0))

