# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

class RootTable extends FlatBuffer:
	enum {
		VT_MY_STRING = 4
	}

	## TODO: create a useful doc comment for the init function
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## TODO: create a useful doc comment for the verify function
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_offset(verifier, VT_MY_STRING)
			and verify_string( verifier, VT_MY_STRING )
			and verify_end_table(verifier)
		)

	## Return true if my_string is present in the buffer, else false
	func my_string_is_present() -> bool:
		return get_field_offset( VT_MY_STRING )

	func my_string() -> String:
		var field_start: int = get_offset_field_start( VT_MY_STRING )
		if not field_start: return ''
		return decode_variant( field_start, TYPE_STRING )


## TODO: Write a Doc Comment for the builder
class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_my_string( my_string_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_MY_STRING, my_string_offset )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_RootTable( _fbb: FlatBufferBuilder,
		my_string: int ) -> int :
	var builder: RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_my_string( my_string );
	return builder.finish();

## TODO: create a doc comment for the get_RootTable function
static func get_RootTable( _bytes: PackedByteArray ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _bytes.decode_u32(0))

