# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

## Enum Used for testing
enum TestEnum {
	## Zero
	ZERO = 0,
	## One
	ONE = 1
}

## Union of Table A and Table B Used for testing
enum TestUnion {
	NONE = 0,
	## First union Memmber
	TEST_TABLE_A = 1,
	## Second Union Memeber
	TEST_TABLE_B = 2
}

## Verify the integrity of the TestUnion union data
static func test_union_verify(verifier:FlatBufferVerifier, value:Variant, type:TestUnion) -> bool: 
	match type:
		TestUnion.TEST_TABLE_A:
			var test_table_a: TestTableA = value
			return test_table_a.verify(verifier)
		TestUnion.TEST_TABLE_B:
			var test_table_b: TestTableB = value
			return test_table_b.verify(verifier)
	return false

## Struct Used for testing
class TestStruct extends FlatBuffer:
	const _fb_struct_size: int = 8

	## Initialize the TestStruct with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		if packed_bytes.is_empty():
			packed_bytes = PackedByteArray()
			if packed_bytes.resize( _fb_struct_size ) != OK:
				printerr('unable to resize byte array')
		assert(offset + _fb_struct_size <= packed_bytes.size())
		assign_buffer( packed_bytes, offset )

	## Field A
	var a: int :
		get(): return _fb_bytes.decode_s32(_fb_start + 0)
		set(v): _fb_bytes.encode_s32(_fb_start + 0, v)

	## Field B
	var b: int :
		get(): return _fb_bytes.decode_s32(_fb_start + 4)
		set(v): _fb_bytes.encode_s32(_fb_start + 4, v)


## Create a new TestStruct with the provided field values
static func create_TestStruct(
		_a: int,
		_b: int ) -> TestStruct :
	var val: TestStruct = TestStruct.new()
	val.b = _b;
	val.a = _a;
	return val

## Table A Used for testing
class TestTableA extends FlatBuffer:
	enum {
		VT_A = 4
	}

	## Initialize the TestStruct with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the TestStruct data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_field_s32(verifier, VT_A, 4)
			and verify_end_table(verifier)
		)

	## Return true if a is present in the buffer, else false
	func a_is_present() -> bool:
		return get_field_offset( VT_A )

	## Field A
	func a() -> int:
		var field_start: int = get_inline_field_start( VT_A )
		if not field_start: return 0
		return _fb_bytes.decode_s32( field_start )


## Builder class for TestTableA
class TestTableABuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Add the a field to the TestTableA table
	func add_a( a: int ) -> void:
		fbb_.add_element_int_default( TestTableA.VT_A, a, 0 )

	## Finish building the TestTableA table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a TestTableA table in one go using the provided [param _fbb]
static func create_TestTableA( _fbb: FlatBufferBuilder,
		a: int ) -> int :
	var builder: TestTableABuilder = TestTableABuilder.new( _fbb );
	builder.add_a( a );
	return builder.finish();

## Table B Used for testing
class TestTableB extends FlatBuffer:
	enum {
		VT_B = 4
	}

	## Initialize the TestTableA with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the TestTableA data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_field_s32(verifier, VT_B, 4)
			and verify_end_table(verifier)
		)

	## Return true if b is present in the buffer, else false
	func b_is_present() -> bool:
		return get_field_offset( VT_B )

	## Field B
	func b() -> int:
		var field_start: int = get_inline_field_start( VT_B )
		if not field_start: return 0
		return _fb_bytes.decode_s32( field_start )


## Builder class for TestTableB
class TestTableBBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Add the b field to the TestTableB table
	func add_b( b: int ) -> void:
		fbb_.add_element_int_default( TestTableB.VT_B, b, 0 )

	## Finish building the TestTableB table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a TestTableB table in one go using the provided [param _fbb]
static func create_TestTableB( _fbb: FlatBufferBuilder,
		b: int ) -> int :
	var builder: TestTableBBuilder = TestTableBBuilder.new( _fbb );
	builder.add_b( b );
	return builder.finish();

## Root Table Used for testing
class RootTable extends FlatBuffer:
	const _vector_schema = preload( 'vector_generated.gd' )

	enum {
		VT_SCALARS = 4,
		VT_ENUMS = 6,
		VT_STRINGS = 8,
		VT_GODOT_STRUCTS = 10,
		VT_CUSTOM_STRUCTS = 12,
		VT_TABLES = 14,
		VT_UNIONS_TYPE = 16,
		VT_UNIONS = 18
	}

	## Initialize the TestTableB with the provided [param packed_bytes] at the given [param offset]
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## Verify the integrity of the TestTableB data
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_offset(verifier, VT_SCALARS)
			and verify_vector_s32(verifier, VT_SCALARS)
			and verify_offset(verifier, VT_ENUMS)
			and verify_vector_u8(verifier, VT_ENUMS)
			and verify_offset(verifier, VT_STRINGS)
			and verify_vector_u32(verifier, VT_STRINGS)
			and verify_vector_of_variant(verifier, VT_STRINGS, TYPE_STRING)
			and verify_offset(verifier, VT_GODOT_STRUCTS)
			and verify_vector_of_variant(verifier, VT_GODOT_STRUCTS, TYPE_VECTOR3)
			and verify_offset(verifier, VT_CUSTOM_STRUCTS)
			and verify_vector(verifier, VT_CUSTOM_STRUCTS, 8, false )
			and verify_offset(verifier, VT_TABLES)
			and verify_vector_u32(verifier, VT_TABLES)
			and tables_verify(verifier)
			and verify_offset(verifier, VT_UNIONS_TYPE)
			and verify_vector_u8(verifier, VT_UNIONS_TYPE)
			and verify_offset(verifier, VT_UNIONS)
			and verify_vector_u32(verifier, VT_UNIONS)
			and unions_verify(verifier)
			and verify_end_table(verifier)
		)

	## Vector of Scalars
	func scalars_size() -> int:
		var array_start: int = get_offset_field_start( VT_SCALARS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Scalars
	## Access elements of scalars by [param index]
	func scalars_at( index: int ) -> int:
		var array_start: int = get_offset_field_start( VT_SCALARS )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes.decode_s32( array_start + index * 4)

	## Vector of Scalars
	## Decode and return all elements of scalars as an [PackedInt32Array]
	func scalars() -> PackedInt32Array:
		var array_start: int = get_offset_field_start( VT_SCALARS )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array_end: int = array_start + array_size * 4
		return _fb_bytes.slice( array_start, array_end ).to_int32_array()

	## Vector of Enums
	func enums_size() -> int:
		var array_start: int = get_offset_field_start( VT_ENUMS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Enums
	## Access elements of enums by [param index]
	func enums_at( index: int ) -> TestEnum:
		var array_start: int = get_offset_field_start( VT_ENUMS )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes[array_start + index]

	## Vector of Enums
	## Decode and return all elements of enums as an [PackedByteArray]
	func enums() -> PackedByteArray:
		var array_start: int = get_offset_field_start( VT_ENUMS )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	## Vector of Strings
	func strings_size() -> int:
		var array_start: int = get_offset_field_start( VT_STRINGS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Strings
	func strings_at( index: int ) -> String:
		var array_start: int = get_offset_field_start( VT_STRINGS )
		if not array_start: return ''
		array_start += 4
		var string_start: int = array_start + index * 4
		string_start += _fb_bytes.decode_u32( string_start )
		return decode_variant( string_start, TYPE_STRING )

	## Vector of Strings
	func strings() -> PackedStringArray:
		var array_start: int = get_offset_field_start( VT_STRINGS )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: PackedStringArray
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var idx: int = array_start + i * 4
			var element_start: int = idx + _fb_bytes.decode_u32( idx )
			array[i] = decode_variant( element_start, TYPE_STRING )
		return array

	## Vector of Godot Structs
	func godot_structs_size() -> int:
		var array_start: int = get_offset_field_start( VT_GODOT_STRUCTS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Godot Structs
	func godot_structs_at( idx: int ) -> Vector3:
		var field_start: int = get_offset_field_start( VT_GODOT_STRUCTS )
		assert(field_start, 'Field "godot_structs" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 12
		return decode_variant( element_offset, TYPE_VECTOR3 )

	## Vector of Godot Structs
	func godot_structs() -> PackedVector3Array:
		var field_start: int = get_offset_field_start( VT_GODOT_STRUCTS )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 12 ) \
				.to_vector3_array()

	## Vector of Custom Structs
	func custom_structs_size() -> int:
		var array_start: int = get_offset_field_start( VT_CUSTOM_STRUCTS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Custom Structs
	func custom_structs_at( idx: int, into: TestStruct = null ) -> TestStruct:
		var field_start: int = get_offset_field_start( VT_CUSTOM_STRUCTS )
		assert(field_start, 'Field "custom_structs" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 8
		if into:
			into.assign_buffer(_fb_bytes, element_offset)
			return into
		return _vector_schema.TestStruct.new( _fb_bytes, element_offset )

	## Vector of Custom Structs
	func custom_structs() -> Array[TestStruct]:
		var field_start: int = get_offset_field_start( VT_CUSTOM_STRUCTS )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		var array: Array[TestStruct]
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			array[i] = _vector_schema.TestStruct.new(_fb_bytes, array_start + i * 8 )
		return array

	## Vector of Tables
	func tables_verify(verifier:FlatBufferVerifier) -> bool:
		var tmp := _vector_schema.TestTableA.new()
		for i in tables_size():
			if not tables_at(i, tmp).verify(verifier):
				return false
		return true

	## Vector of Tables
	func tables_size() -> int:
		var array_start: int = get_offset_field_start( VT_TABLES )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Tables
	func tables_at( idx: int, into: TestTableA = null ) -> TestTableA:
		var field_start: int = get_offset_field_start( VT_TABLES )
		assert(field_start, 'Field "tables" is not present in buffer' )

		# The field is a vector of table, so the inline data is a vector of
		# offsets to the element location.

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_pos: int = array_start + idx * 4
		var element_offset: int = _fb_bytes.decode_u32(element_pos)
		if into:
			into.assign_buffer(_fb_bytes, element_pos + element_offset)
			return into
		return _vector_schema.TestTableA.new( _fb_bytes, element_pos + element_offset )

	## Vector of Tables
	func tables() -> Array:
		var array_start: int = get_offset_field_start( VT_TABLES )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var p: int = array_start + i * 4
			array[i] = _vector_schema.TestTableA.new( _fb_bytes, p + _fb_bytes.decode_u32( p ) )
		return array

	func unions_type_size() -> int:
		var array_start: int = get_offset_field_start( VT_UNIONS_TYPE )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Access elements of unions_type by [param index]
	func unions_type_at( index: int ) -> TestUnion:
		var array_start: int = get_offset_field_start( VT_UNIONS_TYPE )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes[array_start + index]

	## Decode and return all elements of unions_type as an [Array]
	func unions_type() -> Array:
		var array_start: int = get_offset_field_start( VT_UNIONS_TYPE )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	## Return true if unions is present in the buffer, else false
	func unions_is_present() -> bool:
		return get_field_offset( VT_UNIONS )

	## Vector of Unions
	func unions_verify(verifier:FlatBufferVerifier) -> bool:
		for i:int in unions_size():
			if not _vector_schema.test_union_verify(verifier, unions_at(i), unions_type_at(i)):
				return false
		return true

	## Vector of Unions
	func unions_size() -> int:
		var array_start: int = get_offset_field_start( VT_UNIONS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Vector of Unions
	func unions_at( idx: int, into: Variant = null ) -> Variant:
		var field_start: int = get_offset_field_start( VT_UNIONS )
		assert(field_start, 'Field "unions" is not present in buffer' )

		# The field is a vector of union, to decode the
		# content, we need to use the paired *_type vector
		var type:TestUnion = unions_type_at(idx)
		assert(type, 'unions_type is null' )

		# The inline data is a vector of offsets to the element location.
		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4 # (siseof uint32_t)
		var element_pos: int = array_start + idx * 4
		var element_offset: int = _fb_bytes.decode_u32(element_pos)
		if into:
			into.assign_buffer( _fb_bytes, element_pos + element_offset)
			return into

		match type:
			TestUnion.TEST_TABLE_A:
				return _vector_schema.TestTableA.new( _fb_bytes, element_pos + element_offset )
			TestUnion.TEST_TABLE_B:
				return _vector_schema.TestTableB.new( _fb_bytes, element_pos + element_offset )
		return null

	## Vector of Unions
	func unions() -> Array:
		var field_start: int = get_offset_field_start( VT_UNIONS )
		assert(field_start, 'Field "unions" is not present in buffer' )

		# The field is a vector of union, to decode the
		# content, we need to use the paired union_type vector
		var types:PackedByteArray = unions_type()
		assert(not types.is_empty(), 'unions_types is empty' )

		# The inline data is a vector of offsets to the element location.
		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start: int = field_start + 4 # sizeof(uint32_t)

		var result:Array = []
		if result.resize(array_size):
			assert(false, 'Failure to resize result array.')

		for i in array_size:
			var type:TestUnion = types[i] as TestUnion
			var element_pos: int = array_start + i * 4
			var element_offset: int = _fb_bytes.decode_u32(element_pos)
			match type:
				TestUnion.TEST_TABLE_A:
					result[i] = _vector_schema.TestTableA.new( _fb_bytes, element_pos + element_offset )
				TestUnion.TEST_TABLE_B:
					result[i] = _vector_schema.TestTableB.new( _fb_bytes, element_pos + element_offset )
		return result


## Builder class for RootTable
class RootTableBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## Initialize the builder with the provided [param _fbb]
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## Add the scalars field to the RootTable table
	func add_scalars( scalars_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_SCALARS, scalars_offset )

	## Add the enums field to the RootTable table
	func add_enums( enums_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_ENUMS, enums_offset )

	## Add the strings field to the RootTable table
	func add_strings( strings_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_STRINGS, strings_offset )

	## Add the godot_structs field to the RootTable table
	func add_godot_structs( godot_structs_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_GODOT_STRUCTS, godot_structs_offset )

	## Add the custom_structs field to the RootTable table
	func add_custom_structs( custom_structs_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_CUSTOM_STRUCTS, custom_structs_offset )

	## Add the tables field to the RootTable table
	func add_tables( tables_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_TABLES, tables_offset )

	## Add the unions_type field to the RootTable table
	func add_unions_type( unions_type_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_UNIONS_TYPE, unions_type_offset )

	## Add the unions field to the RootTable table
	func add_unions( unions_offset: int ) -> void:
		fbb_.add_offset( RootTable.VT_UNIONS, unions_offset )

	## Finish building the RootTable table and return the offset
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## Create a RootTable table in one go using the provided [param _fbb]
static func create_RootTable( _fbb: FlatBufferBuilder,
		scalars: int,
		enums: int,
		strings: int,
		godot_structs: int,
		custom_structs: int,
		tables: int,
		unions_type: int,
		unions: int ) -> int :
	var builder: RootTableBuilder = RootTableBuilder.new( _fbb );
	builder.add_unions( unions );
	builder.add_unions_type( unions_type );
	builder.add_tables( tables );
	builder.add_custom_structs( custom_structs );
	builder.add_godot_structs( godot_structs );
	builder.add_strings( strings );
	builder.add_enums( enums );
	builder.add_scalars( scalars );
	return builder.finish();

## Get the RootTable from the provided [param _bytes]
static func get_RootTable( _bytes: PackedByteArray ) -> RootTable:
	assert(not _bytes.is_empty())
	return RootTable.new(_bytes, _bytes.decode_u32(0))

