# automatically generated by the FlatBuffers compiler, do not modify

@tool
# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

enum Color_ {
	RED = 0,
	GREEN = 1,
	BLUE = 2
}

enum Equipment {
	NONE = 0,
	WEAPON = 1
}

## TODO: create a doc comment for the verify_Equipment function
static func equipment_verify(verifier:FlatBufferVerifier, value:Variant, type:Equipment) -> bool: 
	match type:
		Equipment.WEAPON:
			var weapon: Weapon = value
			return weapon.verify(verifier)
	return false

class Monster extends FlatBuffer:
	const _Monster_schema = preload( 'Monster_generated.gd' )

	enum {
		VT_POS = 4,
		VT_MANA = 6,
		VT_HP = 8,
		VT_NAME = 10,
		VT_FRIENDLY = 12,
		VT_INVENTORY = 14,
		VT_COLOR = 16,
		VT_WEAPONS = 18,
		VT_EQUIPPED_TYPE = 20,
		VT_EQUIPPED = 22,
		VT_PATH = 24
	}

	## TODO: create a useful doc comment for the init function
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## TODO: create a useful doc comment for the verify function
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_variant(verifier, VT_POS, TYPE_VECTOR3)
			and verify_field_s16(verifier, VT_MANA, 2)
			and verify_field_s16(verifier, VT_HP, 2)
			and verify_offset(verifier, VT_NAME)
			and verify_string( verifier, VT_NAME )
			and verify_offset(verifier, VT_INVENTORY)
			and verify_vector_u8(verifier, VT_INVENTORY)
			and verify_field_s8(verifier, VT_COLOR, 1)
			and verify_offset(verifier, VT_WEAPONS)
			and verify_vector_u32(verifier, VT_WEAPONS)
			and weapons_verify(verifier)
			and verify_field_u8(verifier, VT_EQUIPPED_TYPE, 1)
			and verify_offset(verifier, VT_EQUIPPED)
			and _Monster_schema.equipment_verify(verifier, equipped(), equipped_type())
			and verify_offset(verifier, VT_PATH)
			and verify_vector_u32(verifier, VT_PATH)
			and verify_end_table(verifier)
		)

	## Return true if pos is present in the buffer, else false
	func pos_is_present() -> bool:
		return get_field_offset( VT_POS )

	func pos() -> Vector3:
		var field_start: int = get_inline_field_start( VT_POS )
		return decode_variant( field_start, TYPE_VECTOR3 )

	## Return true if mana is present in the buffer, else false
	func mana_is_present() -> bool:
		return get_field_offset( VT_MANA )

	func mana() -> int:
		var field_start: int = get_inline_field_start( VT_MANA )
		if not field_start: return 150
		return _fb_bytes.decode_s16( field_start )

	## Return true if hp is present in the buffer, else false
	func hp_is_present() -> bool:
		return get_field_offset( VT_HP )

	func hp() -> int:
		var field_start: int = get_inline_field_start( VT_HP )
		if not field_start: return 100
		return _fb_bytes.decode_s16( field_start )

	## Return true if name is present in the buffer, else false
	func name_is_present() -> bool:
		return get_field_offset( VT_NAME )

	func name() -> String:
		var field_start: int = get_offset_field_start( VT_NAME )
		if not field_start: return ''
		return decode_variant( field_start, TYPE_STRING )

	func inventory_size() -> int:
		var array_start: int = get_offset_field_start( VT_INVENTORY )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	## Access elements of inventory by [param index]
	func inventory_at( index: int ) -> int:
		var array_start: int = get_offset_field_start( VT_INVENTORY )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes[array_start + index]

	## Decode and return all elements of inventory as an [PackedByteArray]
	func inventory() -> PackedByteArray:
		var array_start: int = get_offset_field_start( VT_INVENTORY )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	## Return true if color is present in the buffer, else false
	func color_is_present() -> bool:
		return get_field_offset( VT_COLOR )

	func color() -> Color_:
		var field_start: int = get_inline_field_start( VT_COLOR )
		if not field_start: return 2 as Color_
		var decoded: Color_ = _fb_bytes.decode_s8( field_start )
		return decoded

	func weapons_verify(verifier:FlatBufferVerifier) -> bool:
		var tmp := _Monster_schema.Weapon.new()
		for i in weapons_size():
			if not weapons_at(i, tmp).verify(verifier):
				return false
		return true

	func weapons_size() -> int:
		var array_start: int = get_offset_field_start( VT_WEAPONS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func weapons_at( idx: int, into: Weapon = null ) -> Weapon:
		var field_start: int = get_offset_field_start( VT_WEAPONS )
		assert(field_start, 'Field "weapons" is not present in buffer' )

		# The field is a vector of table, so the inline data is a vector of
		# offsets to the element location.

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_pos: int = array_start + idx * 4
		var element_offset: int = _fb_bytes.decode_u32(element_pos)
		if into:
			into.assign_buffer(_fb_bytes, element_pos + element_offset)
			return into
		return _Monster_schema.Weapon.new( _fb_bytes, element_pos + element_offset )

	func weapons() -> Array:
		var array_start: int = get_offset_field_start( VT_WEAPONS )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var p: int = array_start + i * 4
			array[i] = _Monster_schema.Weapon.new( _fb_bytes, p + _fb_bytes.decode_u32( p ) )
		return array

	## Return true if equipped is present in the buffer, else false
	func equipped_is_present() -> bool:
		return get_field_offset( VT_EQUIPPED )

	## TODO: Write a doc comment for the union_type accessor
	func equipped_type() -> Equipment:
		var field_start: int = get_inline_field_start( VT_EQUIPPED_TYPE )
		if not field_start: return 0 as Equipment
		var decoded: Equipment = _fb_bytes.decode_u8( field_start )
		return decoded

	func equipped() -> Variant:
		var field_start: int = get_offset_field_start( VT_EQUIPPED )
		if not field_start: return null
		match( equipped_type() ):
			_Monster_schema.Equipment.WEAPON:
				return _Monster_schema.Weapon.new( _fb_bytes, field_start )
		return null

	func path_size() -> int:
		var array_start: int = get_offset_field_start( VT_PATH )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func path_at( idx: int ) -> Vector3:
		var field_start: int = get_offset_field_start( VT_PATH )
		assert(field_start, 'Field "path" is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var element_offset: int = array_start + idx * 12
		return decode_variant( element_offset, TYPE_VECTOR3 )

	func path() -> PackedVector3Array:
		var field_start: int = get_offset_field_start( VT_PATH )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 12 ) \
				.to_vector3_array()


## TODO: Write a Doc Comment for the builder
class MonsterBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_pos( pos: Vector3 ) -> void:
		fbb_.add_variant( Monster.VT_POS, pos, TYPE_VECTOR3 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_mana( mana: int ) -> void:
		fbb_.add_element_short_default( Monster.VT_MANA, mana, 150 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_hp( hp: int ) -> void:
		fbb_.add_element_short_default( Monster.VT_HP, hp, 100 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_name( name_offset: int ) -> void:
		fbb_.add_offset( Monster.VT_NAME, name_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_inventory( inventory_offset: int ) -> void:
		fbb_.add_offset( Monster.VT_INVENTORY, inventory_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_color( color: Color_ ) -> void:
		fbb_.add_element_byte( Monster.VT_COLOR, color )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_weapons( weapons_offset: int ) -> void:
		fbb_.add_offset( Monster.VT_WEAPONS, weapons_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_equipped_type( equipped_type: Equipment ) -> void:
		fbb_.add_element_ubyte( Monster.VT_EQUIPPED_TYPE, equipped_type )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_equipped( equipped_offset: int ) -> void:
		fbb_.add_offset( Monster.VT_EQUIPPED, equipped_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_path( path_offset: int ) -> void:
		fbb_.add_offset( Monster.VT_PATH, path_offset )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_Monster( _fbb: FlatBufferBuilder,
		pos: Vector3,
		mana: int,
		hp: int,
		name: int,
		inventory: int,
		color: Color_,
		weapons: int,
		equipped_type: Equipment,
		equipped: int,
		path: int ) -> int :
	var builder: MonsterBuilder = MonsterBuilder.new( _fbb );
	builder.add_path( path );
	builder.add_equipped( equipped );
	builder.add_weapons( weapons );
	builder.add_inventory( inventory );
	builder.add_name( name );
	builder.add_pos( pos );
	builder.add_hp( hp );
	builder.add_mana( mana );
	builder.add_equipped_type( equipped_type );
	builder.add_color( color );
	return builder.finish();

class Weapon extends FlatBuffer:
	enum {
		VT_NAME = 4,
		VT_DAMAGE = 6
	}

	## TODO: create a useful doc comment for the init function
	func _init( packed_bytes: PackedByteArray = [], offset: int = 0) -> void:
		assign_buffer( packed_bytes, offset )

	## TODO: create a useful doc comment for the verify function
	func verify(verifier:FlatBufferVerifier) -> bool:
		verifier.set_buffer(_fb_bytes)
		return (
			verify_table_start(verifier)
			and verify_offset(verifier, VT_NAME)
			and verify_string( verifier, VT_NAME )
			and verify_field_s16(verifier, VT_DAMAGE, 2)
			and verify_end_table(verifier)
		)

	## Return true if name is present in the buffer, else false
	func name_is_present() -> bool:
		return get_field_offset( VT_NAME )

	func name() -> String:
		var field_start: int = get_offset_field_start( VT_NAME )
		if not field_start: return ''
		return decode_variant( field_start, TYPE_STRING )

	## Return true if damage is present in the buffer, else false
	func damage_is_present() -> bool:
		return get_field_offset( VT_DAMAGE )

	func damage() -> int:
		var field_start: int = get_inline_field_start( VT_DAMAGE )
		if not field_start: return 0
		return _fb_bytes.decode_s16( field_start )


## TODO: Write a Doc Comment for the builder
class WeaponBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_name( name_offset: int ) -> void:
		fbb_.add_offset( Weapon.VT_NAME, name_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_damage( damage: int ) -> void:
		fbb_.add_element_short_default( Weapon.VT_DAMAGE, damage, 0 )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_Weapon( _fbb: FlatBufferBuilder,
		name: int,
		damage: int ) -> int :
	var builder: WeaponBuilder = WeaponBuilder.new( _fbb );
	builder.add_name( name );
	builder.add_damage( damage );
	return builder.finish();

## TODO: create a doc comment for the get_Monster function
static func get_Monster( _bytes: PackedByteArray ) -> Monster:
	assert(not _bytes.is_empty())
	return Monster.new(_bytes, _bytes.decode_u32(0))

