# ██████  ███████  █████  ██████  ██ ███    ██  ██████
# ██   ██ ██      ██   ██ ██   ██ ██ ████   ██ ██
# ██████  █████   ███████ ██   ██ ██ ██ ██  ██ ██   ███
# ██   ██ ██      ██   ██ ██   ██ ██ ██  ██ ██ ██    ██
# ██   ██ ███████ ██   ██ ██████  ██ ██   ████  ██████
# Reading Orc FlatBuffers

# Now that we have successfully created an Orc FlatBuffer, the monster data can
# be saved, sent over a network, etc. Let's now adventure into the inverse, and
# access a FlatBuffer.

# This section requires the same import/include, namespace, etc. requirements
# as before:
# #include "monster_generated.h" // This was generated by `flatc`.

const schema = preload("res://tests/fb_monster/Monster_generated.gd")

# using namespace MyGame::Sample; // Specified in the schema.

# Then, assuming you have a buffer of bytes received from disk, network, etc.,
# you can start accessing the buffer like so:

func read_orc_flatbuffer( bytes:PackedByteArray ) -> void:
	# Again, make sure you read the bytes in BINARY mode, otherwise the code
	# below won't work.
	# uint8_t *buffer_pointer = /* the data you just read */;

	# Get a pointer to the root object inside the buffer.
	# auto monster = GetMonster(buffer_pointer);
	var monster:schema.Monster = schema.get_Monster( bytes )

	# `monster` is of type `Monster *`.
	# NOTE: in gdscript monster is a schema.Monster: a gdextension object class
	# override originally derived from godot::RefCounted, that acts like a
	# stringview over a Variant with internal PackedByteArray type.

	# Note: root object pointers are NOT the same as `buffer_pointer`.
	# `GetMonster` is a convenience function that calls `GetRoot<Monster>`, the
	# latter is also available for non-root types.
	
	# NOTE: GetRoot is not implemented
	# But if I was to, it might look something like:
	# static func get_root( script:GDScript, bytes:PackedByteArray ) -> Object

	# If you look in the generated files from the schema compiler, you will see
	# it generated accessors for all non-deprecated fields. For example:
	# auto hp = monster->hp();
	var hp:int = monster.hp()
	# auto mana = monster->mana();
	var mana:int = monster.mana()
	# auto name = monster->name()->c_str();
	var name:String = monster.name()

	# These should hold 300, 150, and "Orc" respectively.
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( 300, hp,  "monster.hp()" )
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( 150, mana,  "monster.mana()" )
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( "Orc", name , "monster.name()" )

	# Note: The default value 150 wasn't stored in mana, but we are still able
	# to retrieve it.

	# To access sub-objects, in the case of our pos, which is a Vec3:
	# auto pos = monster->pos();
	var pos:Vector3 = monster.pos()
	# auto x = pos->x();
	var x:float = pos.x
	# auto y = pos->y();
	var y:float = pos.y
	# auto z = pos->z();
	var z:float = pos.z

	# x, y, and z will contain 1.0, 2.0, and 3.0, respectively.
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( x, 1.0, "monster.pos.x()" )
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( y, 2.0, "monster.pos.y()" )
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( z, 3.0, "monster.pos.z()" )

	# Note: Had we not set pos during serialization, it would be a null-value.

	# Similarly, we can access elements of the inventory vector by indexing it.
	# You can also iterate over the length of the array/vector representing the
	# FlatBuffers vector.
	# auto inv = monster->inventory(); // A pointer to a `flatbuffers::Vector<>`.
	var inv:PackedByteArray = monster.inventory()
	# auto inv_len = inv->size();
	var inv_len:int = inv.size() # 10
	# auto third_item = inv->Get(2);
	@warning_ignore("untyped_declaration")
	var third_item = inv[2]

	# NOTE: monster.inventory() can, depending on type, decode and returns the
	# the whole array. I have provided *_size(), and *_at(idx) to help.
	@warning_ignore("return_value_discarded")
	test.TEST_EQ(10, inv_len, "monster.inventory().size()")
	@warning_ignore("return_value_discarded")
	test.TEST_EQ(2, third_item, "monster.inventory().size()")
	@warning_ignore("return_value_discarded")
	test.TEST_EQ(10, monster.inventory_size(), "monster.inventory_size()")
	@warning_ignore("return_value_discarded")
	test.TEST_EQ(2, monster.inventory_at(2), "monster.inventory_at(2)")

	# For vectors of tables, you can access the elements like any other vector,
	# except you need to handle the result as a FlatBuffer table:
	# auto weapons = monster->weapons(); // A pointer to a `flatbuffers::Vector<>`.
	var weapons:Array = monster.weapons()
	# auto weapon_len = weapons->size();
	var weapon_len:int = weapons.size()
	var weapon_len_:int = monster.weapons_size()
	
	# NOTE: [] operator does not return a typed object.
	var second_weapon:schema.Weapon = weapons[1]
	
	# auto second_weapon_name = weapons->Get(1)->name()->str();
	var second_weapon_name:String = second_weapon.name()
	# the _at function can return a typed object
	var second_weapon_name_:String = monster.weapons_at(1).name()
	
	# auto second_weapon_damage = weapons->Get(1)->damage()
	var second_weapon_damage:int = second_weapon.damage()
	var second_weapon_damage_:int = monster.weapons_at(1).damage()

	@warning_ignore("return_value_discarded")
	test.TEST_EQ(2, weapon_len, "weapons.size()")
	@warning_ignore("return_value_discarded")
	test.TEST_EQ(2, weapon_len_, "monster.weapons_size()")

	@warning_ignore("return_value_discarded")
	test.TEST_EQ("Axe", second_weapon_name, "weapons.size()")
	@warning_ignore("return_value_discarded")
	test.TEST_EQ("Axe", second_weapon_name_, "monster.weapons_size()")

	@warning_ignore("return_value_discarded")
	test.TEST_EQ(5, second_weapon_damage, "weapons.size()")
	@warning_ignore("return_value_discarded")
	test.TEST_EQ(5, second_weapon_damage_, "monster.weapons_size()")

	# Last, we can access our Equipped FlatBuffer union. Just like when we
	# created the union, we need to get both parts of the union: the type and
	# the data.

	# We can access the type to dynamically cast the data as needed (since the
	# union only stores a FlatBuffer table).
	# auto union_type = monster.equipped_type();
	var union_type:schema.Equipment = monster.equipped_type()
	@warning_ignore("return_value_discarded")
	test.TEST_EQ( schema.Equipment.WEAPON, union_type, "monster.equipped_type()" )

	# if (union_type == Equipment_Weapon) {
	#   auto weapon = static_cast<const Weapon*>(monster->equipped()); // Requires `static_cast`
	#                                                                  // to type `const Weapon*`.
	#   auto weapon_name = weapon->name()->str(); // "Axe"
	#   auto weapon_damage = weapon->damage();    // 5
	# }
	match union_type:
		schema.Equipment.WEAPON:
			var weapon:schema.Weapon = monster.equipped()
			var weapon_name:String = weapon.name()
			var weapon_damage:int = weapon.damage()
			@warning_ignore("return_value_discarded")
			test.TEST_EQ( weapon_name, "Axe", "weapon_name" )
			@warning_ignore("return_value_discarded")
			test.TEST_EQ( weapon_damage, 5, "weapon_damage" )




## Because we cannot pre-load a script that hasnt been generated yet, the test
## script must load this script after the generated script has been created so
## that this script can preload and use it properly.
## It's a bit convoluted yes.

var test:TestBase
func _init(initiator:TestBase) -> void:
	test = initiator
