# automatically generated by the FlatBuffers compiler, do not modify

# To maintain reference counted PackedByteArray the gdextension type for data
# must be Variant, which triggers these two notices
@warning_ignore_start('unsafe_method_access')
@warning_ignore_start('unsafe_call_argument')

enum Color_ {
	RED = 0,
	GREEN = 1,
	BLUE = 2
}

enum Equipment {
	NONE = 0,
	WEAPON = 1
}

class Monster extends FlatBuffer:
	const _Monster_schema = preload( 'Monster_generated.gd' )

	enum vtable {
		VT_POS = 4,
		VT_MANA = 6,
		VT_HP = 8,
		VT_NAME = 10,
		VT_FRIENDLY = 12,
		VT_INVENTORY = 14,
		VT_COLOR = 16,
		VT_WEAPONS = 18,
		VT_EQUIPPED_TYPE = 20,
		VT_EQUIPPED = 22,
		VT_PATH = 24
	}

	## TODO: create a useful doc comment for the init function
	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	## Return true if pos is present in the buffer, else false
	func pos_is_present() -> bool:
		return get_field_offset( vtable.VT_POS )

	func pos() -> Vector3:
		return get_Vector3( vtable.VT_POS )

	## Return true if mana is present in the buffer, else false
	func mana_is_present() -> bool:
		return get_field_offset( vtable.VT_MANA )

	func mana() -> int:
		var foffset: int = get_field_offset( vtable.VT_MANA )
		if not foffset: return 150
		return _fb_bytes.decode_s16( _fb_start + foffset )

	## Return true if hp is present in the buffer, else false
	func hp_is_present() -> bool:
		return get_field_offset( vtable.VT_HP )

	func hp() -> int:
		var foffset: int = get_field_offset( vtable.VT_HP )
		if not foffset: return 100
		return _fb_bytes.decode_s16( _fb_start + foffset )

	## Return true if name is present in the buffer, else false
	func name_is_present() -> bool:
		return get_field_offset( vtable.VT_NAME )

	func name() -> String:
		var field_start: int = get_field_start( vtable.VT_NAME )
		if not field_start: return ''
		return decode_String( field_start )

	## Return true if inventory is present in the buffer, else false
	func inventory_is_present() -> bool:
		return get_field_offset( vtable.VT_INVENTORY )

	func inventory_size() -> int:
		var array_start: int = get_field_start( vtable.VT_INVENTORY )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	##decode and return all elements of inventory as an [PackedByteArray]
	func inventory() -> PackedByteArray:
		var array_start: int = get_field_start( vtable.VT_INVENTORY )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		return _fb_bytes.slice( array_start, array_start + array_size )

	##Access elements of inventory by [param index]
	func inventory_at( index: int ) -> int:
		var array_start: int = get_field_start( vtable.VT_INVENTORY )
		assert(array_start, 'access to invalid vector of enum')
		array_start += 4
		return _fb_bytes[array_start + index]

	## Return true if color is present in the buffer, else false
	func color_is_present() -> bool:
		return get_field_offset( vtable.VT_COLOR )

	func color() -> Color_:
		var foffset: int = get_field_offset( vtable.VT_COLOR )
		if not foffset: return 2 as Color_
		var decoded: Color_ = _fb_bytes.decode_s8( _fb_start + foffset )
		return decoded

	## Return true if weapons is present in the buffer, else false
	func weapons_is_present() -> bool:
		return get_field_offset( vtable.VT_WEAPONS )

	func weapons_size() -> int:
		var array_start: int = get_field_start( vtable.VT_WEAPONS )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func weapons() -> Array:
		var array_start: int = get_field_start( vtable.VT_WEAPONS )
		if not array_start: return []
		var array_size: int = _fb_bytes.decode_u32( array_start )
		array_start += 4
		var array: Array
		if array.resize( array_size ) != OK: return []
		for i: int in array_size:
			var p: int = array_start + i * 4
			array[i] = _Monster_schema.Weapon.new( _fb_bytes, p + _fb_bytes.decode_u32( p ) )
		return array

	func weapons_at( idx: int, into: Weapon = null ) -> Weapon:
		var field_start: int = get_field_start( vtable.VT_WEAPONS )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		var relative_offset: int = array_start + idx * 4
		var offset: int = relative_offset + _fb_bytes.decode_u32( relative_offset )
		if into:
			into._fb_bytes = _fb_bytes
			into._fb_start = relative_offset
			return into
		return _Monster_schema.Weapon.new( _fb_bytes, offset )

	## Return true if equipped_type is present in the buffer, else false
	func equipped_type_is_present() -> bool:
		return get_field_offset( vtable.VT_EQUIPPED_TYPE )

	func equipped_type() -> Equipment:
		var foffset: int = get_field_offset( vtable.VT_EQUIPPED_TYPE )
		if not foffset: return 0 as Equipment
		var decoded: Equipment = _fb_bytes.decode_u8( _fb_start + foffset )
		return decoded

	## Return true if equipped is present in the buffer, else false
	func equipped_is_present() -> bool:
		return get_field_offset( vtable.VT_EQUIPPED )

	func equipped() -> Variant:
		var field_start: int = get_field_start( vtable.VT_EQUIPPED )
		if not field_start: return null
		match( equipped_type() ):
			Equipment.WEAPON:
				return _Monster_schema.Weapon.new( _fb_bytes, field_start )
			_: pass
		return null

	## Return true if path is present in the buffer, else false
	func path_is_present() -> bool:
		return get_field_offset( vtable.VT_PATH )

	func path_size() -> int:
		var array_start: int = get_field_start( vtable.VT_PATH )
		if not array_start: return 0
		return _fb_bytes.decode_u32( array_start )

	func path() -> PackedVector3Array:
		var field_start: int = get_field_start( vtable.VT_PATH )
		if not field_start: return []

		var array_size: int = _fb_bytes.decode_u32( field_start )
		var array_start:int = field_start + 4
		return _fb_bytes.slice(
				array_start, array_start + array_size * 12 ) \
				.to_vector3_array()

	func path_at( idx: int ) -> Vector3:
		var field_start: int = get_field_start( vtable.VT_PATH )
		assert(field_start, 'Field is not present in buffer' )

		var array_size: int = _fb_bytes.decode_u32( field_start )
		assert( idx < array_size, 'index is out of bounds')

		var array_start: int = field_start + 4
		return decode_Vector3( array_start + idx * 12 )


## TODO: Write a Doc Comment for the builder
class MonsterBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_pos( pos: Vector3 ) -> void:
		fbb_.add_Vector3( Monster.vtable.VT_POS, pos )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_mana( mana: int ) -> void:
		fbb_.add_element_short_default( Monster.vtable.VT_MANA, mana, 150 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_hp( hp: int ) -> void:
		fbb_.add_element_short_default( Monster.vtable.VT_HP, hp, 100 )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_name( name_offset: int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_NAME, name_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_inventory( inventory_offset: int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_INVENTORY, inventory_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_color( color: Color_ ) -> void:
		fbb_.add_element_byte( Monster.vtable.VT_COLOR, color )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_weapons( weapons_offset: int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_WEAPONS, weapons_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_equipped_type( equipped_type: Equipment ) -> void:
		fbb_.add_element_ubyte( Monster.vtable.VT_EQUIPPED_TYPE, equipped_type )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_equipped( equipped_offset: int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_EQUIPPED, equipped_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_path( path_offset: int ) -> void:
		fbb_.add_offset( Monster.vtable.VT_PATH, path_offset )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_Monster( _fbb: FlatBufferBuilder,
		pos: Vector3,
		mana: int,
		hp: int,
		name: int,
		inventory: int,
		color: Color_,
		weapons: int,
		equipped_type: Equipment,
		equipped: int,
		path: int ) -> int :
	var builder: MonsterBuilder = MonsterBuilder.new( _fbb );
	builder.add_path( path );
	builder.add_equipped( equipped );
	builder.add_weapons( weapons );
	builder.add_inventory( inventory );
	builder.add_name( name );
	builder.add_pos( pos );
	builder.add_hp( hp );
	builder.add_mana( mana );
	builder.add_equipped_type( equipped_type );
	builder.add_color( color );
	return builder.finish();

class Weapon extends FlatBuffer:
	enum vtable {
		VT_NAME = 4,
		VT_DAMAGE = 6
	}

	## TODO: create a useful doc comment for the init function
	func _init( bytes_: PackedByteArray = [], start_: int = 0) -> void:
		_fb_bytes = bytes_; _fb_start = start_

	## Return true if name is present in the buffer, else false
	func name_is_present() -> bool:
		return get_field_offset( vtable.VT_NAME )

	func name() -> String:
		var field_start: int = get_field_start( vtable.VT_NAME )
		if not field_start: return ''
		return decode_String( field_start )

	## Return true if damage is present in the buffer, else false
	func damage_is_present() -> bool:
		return get_field_offset( vtable.VT_DAMAGE )

	func damage() -> int:
		var foffset: int = get_field_offset( vtable.VT_DAMAGE )
		if not foffset: return 0
		return _fb_bytes.decode_s16( _fb_start + foffset )


## TODO: Write a Doc Comment for the builder
class WeaponBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_: int

	## TODO: Write a Doc Comment for the builder's init function
	func _init( _fbb: FlatBufferBuilder ) -> void:
		fbb_ = _fbb
		start_ = _fbb.start_table()

	## TODO: Write a Doc Comment for the builder's add functions
	func add_name( name_offset: int ) -> void:
		fbb_.add_offset( Weapon.vtable.VT_NAME, name_offset )

	## TODO: Write a Doc Comment for the builder's add functions
	func add_damage( damage: int ) -> void:
		fbb_.add_element_short_default( Weapon.vtable.VT_DAMAGE, damage, 0 )

	## TODO: Write a Doc Comment for the builder's finish function
	func finish() -> int:
		var end: int = fbb_.end_table( start_ )
		var o: int = end
		return o;

## TODO: Write a Doc Comment for the static table create function
static func create_Weapon( _fbb: FlatBufferBuilder,
		name: int,
		damage: int ) -> int :
	var builder: WeaponBuilder = WeaponBuilder.new( _fbb );
	builder.add_name( name );
	builder.add_damage( damage );
	return builder.finish();

static func get_Monster( _bytes: PackedByteArray ) -> Monster:
	assert(not _bytes.is_empty())
	return Monster.new(_bytes, _bytes.decode_u32(0))

