# automatically generated by the FlatBuffers compiler, do not modify

static func GetRoot( _bytes : PackedByteArray ) -> Absolute:
	return GetAbsolute( _bytes, _bytes.decode_u32(0) )

static func GetAbsolute( _bytes : PackedByteArray, _start : int = 0 ) -> Absolute:
	if _bytes.is_empty(): return null
	var new_Absolute = Absolute.new()
	new_Absolute.start = _start
	new_Absolute.bytes = _bytes
	return new_Absolute


class Absolute extends FlatBuffer:
	enum vtable{
		VT_VALUE = 4,
		VT_OFFSET = 6
	}

	func value_is_present() -> bool:
		return get_field_offset( vtable.VT_VALUE )

	func value() -> float:
		var foffset = get_field_offset( vtable.VT_VALUE )
		if not foffset: return 0.0
		return bytes.decode_float( start + foffset )

	func offset_is_present() -> bool:
		return get_field_offset( vtable.VT_OFFSET )

	func offset() -> Vector3:
		return GetVector3( vtable.VT_OFFSET )


class AbsoluteBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_value( value : float ) -> void:
		fbb_.add_element_float_default( Absolute.vtable.VT_VALUE, value, 0.0 )

	func add_offset( offset : Vector3 ) -> void:
		fbb_.add_Vector3( Absolute.vtable.VT_OFFSET, offset )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateAbsolute( _fbb : FlatBufferBuilder,
		value : float,
		offset : Vector3 ) -> int :
	var builder = AbsoluteBuilder.new( _fbb );
	builder.add_offset( offset );
	builder.add_value( value );
	return builder.finish();

