# automatically generated by the FlatBuffers compiler, do not modify

static func GetRoot( _bytes : PackedByteArray ) -> Relative:
	return GetRelative( _bytes, _bytes.decode_u32(0) )

static func GetRelative( _bytes : PackedByteArray, _start : int = 0 ) -> Relative:
	if _bytes.is_empty(): return null
	var new_Relative = Relative.new()
	new_Relative.start = _start
	new_Relative.bytes = _bytes
	return new_Relative


class Relative extends FlatBuffer:
	enum vtable{
		VT_VALUE = 4
	}

	func value_is_present() -> bool:
		return get_field_offset( vtable.VT_VALUE )

	func value() -> Vector3:
		return GetVector3( vtable.VT_VALUE )


class RelativeBuilder extends RefCounted:
	var fbb_: FlatBufferBuilder
	var start_ : int

	func _init( _fbb : FlatBufferBuilder ):
		fbb_ = _fbb
		start_ = _fbb.start_table()

	func add_value( value : Vector3 ) -> void:
		fbb_.add_Vector3( Relative.vtable.VT_VALUE, value )

	func finish() -> int:
		var end = fbb_.end_table( start_ )
		var o = end
		return o;


static func CreateRelative( _fbb : FlatBufferBuilder,
		value : Vector3 ) -> int :
	var builder = RelativeBuilder.new( _fbb );
	builder.add_value( value );
	return builder.finish();

