// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VERIFIER_H_
#define FLATBUFFERS_GENERATED_VERIFIER_H_

#pragma clang system_header


#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
			  FLATBUFFERS_VERSION_MINOR == 12 &&
			  FLATBUFFERS_VERSION_REVISION == 19,
			 "Non-compatible flatbuffers version included");

struct MyTable;
struct MyTableBuilder;

struct MyTable FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MyTableBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
	VT_FIRST_FIELD = 4
  };
  int32_t first_field() const {
	return GetField<int32_t>(VT_FIRST_FIELD, 0);
  }
  bool mutate_first_field(int32_t _first_field = 0) {
	return SetField<int32_t>(VT_FIRST_FIELD, _first_field, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
	return VerifyTableStart(verifier) &&
		   VerifyField<int32_t>(verifier, VT_FIRST_FIELD, 4) &&
		   verifier.EndTable();
  }
};

struct MyTableBuilder {
  typedef MyTable Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_first_field(int32_t first_field) {
	fbb_.AddElement<int32_t>(MyTable::VT_FIRST_FIELD, first_field, 0);
  }
  explicit MyTableBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
		: fbb_(_fbb) {
	start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MyTable> Finish() {
	const auto end = fbb_.EndTable(start_);
	auto o = ::flatbuffers::Offset<MyTable>(end);
	return o;
  }
};

inline ::flatbuffers::Offset<MyTable> CreateMyTable(
	::flatbuffers::FlatBufferBuilder &_fbb,
	int32_t first_field = 0) {
  MyTableBuilder builder_(_fbb);
  builder_.add_first_field(first_field);
  return builder_.Finish();
}

struct MyTable::Traits {
  using type = MyTable;
  static auto constexpr Create = CreateMyTable;
};

inline const MyTable * _Nullable GetMyTable(const void *buf) {
  return ::flatbuffers::GetRoot<MyTable>(buf);
}

inline const MyTable * _Nullable GetSizePrefixedMyTable(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MyTable>(buf);
}

inline MyTable *GetMutableMyTable(void *buf) {
  return ::flatbuffers::GetMutableRoot<MyTable>(buf);
}

inline MyTable * _Nullable GetMutableSizePrefixedMyTable(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<MyTable>(buf);
}

template <bool B = false>
inline bool VerifyMyTableBuffer(
	::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<MyTable>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMyTableBuffer(
	::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<MyTable>(nullptr);
}

inline void FinishMyTableBuffer(
	::flatbuffers::FlatBufferBuilder &fbb,
	::flatbuffers::Offset<MyTable> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMyTableBuffer(
	::flatbuffers::FlatBufferBuilder &fbb,
	::flatbuffers::Offset<MyTable> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_VERIFIER_H_
